// Code generated by kk_etcd_go. DO NOT EDIT.

package api_impl

import (
	"context"

	"gitee.com/cruvie/kk_go_kit/kk_grpc"
	"github.com/cruvie/kk_etcd_go/internal/service_hub/backup/api_def"
	"github.com/cruvie/kk_etcd_go/internal/utils/internal_client"
)

type CServer struct {
	api_def.UnimplementedBackupServer
	ins server
}

func (x *CServer) AllKVsBackup(ctx context.Context, input *api_def.AllKVsBackup_Input) (*api_def.AllKVsBackup_Output, error) {
	ctx = kk_grpc.SetGrpcStage(ctx, internal_client.GlobalStage)
	return x.ins.AllKVsBackup(ctx, input)
}

func (x *CServer) AllKVsRestore(ctx context.Context, input *api_def.AllKVsRestore_Input) (*api_def.AllKVsRestore_Output, error) {
	ctx = kk_grpc.SetGrpcStage(ctx, internal_client.GlobalStage)
	return x.ins.AllKVsRestore(ctx, input)
}

func (x *CServer) Snapshot(ctx context.Context, input *api_def.Snapshot_Input) (*api_def.Snapshot_Output, error) {
	ctx = kk_grpc.SetGrpcStage(ctx, internal_client.GlobalStage)
	return x.ins.Snapshot(ctx, input)
}

func (x *CServer) SnapshotInfo(ctx context.Context, input *api_def.SnapshotInfo_Input) (*api_def.SnapshotInfo_Output, error) {
	ctx = kk_grpc.SetGrpcStage(ctx, internal_client.GlobalStage)
	return x.ins.SnapshotInfo(ctx, input)
}

func (x *CServer) SnapshotRestore(ctx context.Context, input *api_def.SnapshotRestore_Input) (*api_def.SnapshotRestore_Output, error) {
	ctx = kk_grpc.SetGrpcStage(ctx, internal_client.GlobalStage)
	return x.ins.SnapshotRestore(ctx, input)
}
