// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: internal/service_hub/role/api_def/service.proto

package api_def

import (
	_ "gitee.com/cruvie/kk_go_kit/kk_protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_internal_service_hub_role_api_def_service_proto protoreflect.FileDescriptor

const file_internal_service_hub_role_api_def_service_proto_rawDesc = "" +
	"\n" +
	"/internal/service_hub/role/api_def/service.proto\x12\akk_etcd\x1a/internal/service_hub/role/api_def/RoleAdd.proto\x1a2internal/service_hub/role/api_def/RoleDelete.proto\x1a/internal/service_hub/role/api_def/RoleGet.proto\x1a;internal/service_hub/role/api_def/RoleGrantPermission.proto\x1a0internal/service_hub/role/api_def/RoleList.proto\x1a<internal/service_hub/role/api_def/RoleRevokePermission.proto\x1aAvendor/gitee.com/cruvie/kk_go_kit/kk_protobuf/extend_method.proto2\xef\x03\n" +
	"\x04Role\x12A\n" +
	"\aRoleAdd\x12\x16.kk_etcd.RoleAdd.Input\x1a\x17.kk_etcd.RoleAdd.Output\"\x05\x8a\xa6\x1d\x01\x01\x12J\n" +
	"\n" +
	"RoleDelete\x12\x19.kk_etcd.RoleDelete.Input\x1a\x1a.kk_etcd.RoleDelete.Output\"\x05\x8a\xa6\x1d\x01\x01\x12A\n" +
	"\aRoleGet\x12\x16.kk_etcd.RoleGet.Input\x1a\x17.kk_etcd.RoleGet.Output\"\x05\x8a\xa6\x1d\x01\x01\x12e\n" +
	"\x13RoleGrantPermission\x12\".kk_etcd.RoleGrantPermission.Input\x1a#.kk_etcd.RoleGrantPermission.Output\"\x05\x8a\xa6\x1d\x01\x01\x12D\n" +
	"\bRoleList\x12\x17.kk_etcd.RoleList.Input\x1a\x18.kk_etcd.RoleList.Output\"\x05\x8a\xa6\x1d\x01\x01\x12h\n" +
	"\x14RoleRevokePermission\x12#.kk_etcd.RoleRevokePermission.Input\x1a$.kk_etcd.RoleRevokePermission.Output\"\x05\x8a\xa6\x1d\x01\x01B\n" +
	"Z\b/api_defb\x06proto3"

var file_internal_service_hub_role_api_def_service_proto_goTypes = []any{
	(*RoleAdd_Input)(nil),               // 0: kk_etcd.RoleAdd.Input
	(*RoleDelete_Input)(nil),            // 1: kk_etcd.RoleDelete.Input
	(*RoleGet_Input)(nil),               // 2: kk_etcd.RoleGet.Input
	(*RoleGrantPermission_Input)(nil),   // 3: kk_etcd.RoleGrantPermission.Input
	(*RoleList_Input)(nil),              // 4: kk_etcd.RoleList.Input
	(*RoleRevokePermission_Input)(nil),  // 5: kk_etcd.RoleRevokePermission.Input
	(*RoleAdd_Output)(nil),              // 6: kk_etcd.RoleAdd.Output
	(*RoleDelete_Output)(nil),           // 7: kk_etcd.RoleDelete.Output
	(*RoleGet_Output)(nil),              // 8: kk_etcd.RoleGet.Output
	(*RoleGrantPermission_Output)(nil),  // 9: kk_etcd.RoleGrantPermission.Output
	(*RoleList_Output)(nil),             // 10: kk_etcd.RoleList.Output
	(*RoleRevokePermission_Output)(nil), // 11: kk_etcd.RoleRevokePermission.Output
}
var file_internal_service_hub_role_api_def_service_proto_depIdxs = []int32{
	0,  // 0: kk_etcd.Role.RoleAdd:input_type -> kk_etcd.RoleAdd.Input
	1,  // 1: kk_etcd.Role.RoleDelete:input_type -> kk_etcd.RoleDelete.Input
	2,  // 2: kk_etcd.Role.RoleGet:input_type -> kk_etcd.RoleGet.Input
	3,  // 3: kk_etcd.Role.RoleGrantPermission:input_type -> kk_etcd.RoleGrantPermission.Input
	4,  // 4: kk_etcd.Role.RoleList:input_type -> kk_etcd.RoleList.Input
	5,  // 5: kk_etcd.Role.RoleRevokePermission:input_type -> kk_etcd.RoleRevokePermission.Input
	6,  // 6: kk_etcd.Role.RoleAdd:output_type -> kk_etcd.RoleAdd.Output
	7,  // 7: kk_etcd.Role.RoleDelete:output_type -> kk_etcd.RoleDelete.Output
	8,  // 8: kk_etcd.Role.RoleGet:output_type -> kk_etcd.RoleGet.Output
	9,  // 9: kk_etcd.Role.RoleGrantPermission:output_type -> kk_etcd.RoleGrantPermission.Output
	10, // 10: kk_etcd.Role.RoleList:output_type -> kk_etcd.RoleList.Output
	11, // 11: kk_etcd.Role.RoleRevokePermission:output_type -> kk_etcd.RoleRevokePermission.Output
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_internal_service_hub_role_api_def_service_proto_init() }
func file_internal_service_hub_role_api_def_service_proto_init() {
	if File_internal_service_hub_role_api_def_service_proto != nil {
		return
	}
	file_internal_service_hub_role_api_def_RoleAdd_proto_init()
	file_internal_service_hub_role_api_def_RoleDelete_proto_init()
	file_internal_service_hub_role_api_def_RoleGet_proto_init()
	file_internal_service_hub_role_api_def_RoleGrantPermission_proto_init()
	file_internal_service_hub_role_api_def_RoleList_proto_init()
	file_internal_service_hub_role_api_def_RoleRevokePermission_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_service_hub_role_api_def_service_proto_rawDesc), len(file_internal_service_hub_role_api_def_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_service_hub_role_api_def_service_proto_goTypes,
		DependencyIndexes: file_internal_service_hub_role_api_def_service_proto_depIdxs,
	}.Build()
	File_internal_service_hub_role_api_def_service_proto = out.File
	file_internal_service_hub_role_api_def_service_proto_goTypes = nil
	file_internal_service_hub_role_api_def_service_proto_depIdxs = nil
}
