// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: kk_etcd_api_hub/ai/api_def/service.proto

package api_def

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_kk_etcd_api_hub_ai_api_def_service_proto protoreflect.FileDescriptor

const file_kk_etcd_api_hub_ai_api_def_service_proto_rawDesc = "" +
	"\n" +
	"(kk_etcd_api_hub/ai/api_def/service.proto\x12\aapi_def\x1a&kk_etcd_api_hub/ai/api_def/Query.proto2:\n" +
	"\x02AI\x124\n" +
	"\x05Query\x12\x14.api_def.Query.Input\x1a\x15.api_def.Query.OutputB\n" +
	"Z\b/api_defb\x06proto3"

var file_kk_etcd_api_hub_ai_api_def_service_proto_goTypes = []any{
	(*Query_Input)(nil),  // 0: api_def.Query.Input
	(*Query_Output)(nil), // 1: api_def.Query.Output
}
var file_kk_etcd_api_hub_ai_api_def_service_proto_depIdxs = []int32{
	0, // 0: api_def.AI.Query:input_type -> api_def.Query.Input
	1, // 1: api_def.AI.Query:output_type -> api_def.Query.Output
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kk_etcd_api_hub_ai_api_def_service_proto_init() }
func file_kk_etcd_api_hub_ai_api_def_service_proto_init() {
	if File_kk_etcd_api_hub_ai_api_def_service_proto != nil {
		return
	}
	file_kk_etcd_api_hub_ai_api_def_Query_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_etcd_api_hub_ai_api_def_service_proto_rawDesc), len(file_kk_etcd_api_hub_ai_api_def_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kk_etcd_api_hub_ai_api_def_service_proto_goTypes,
		DependencyIndexes: file_kk_etcd_api_hub_ai_api_def_service_proto_depIdxs,
	}.Build()
	File_kk_etcd_api_hub_ai_api_def_service_proto = out.File
	file_kk_etcd_api_hub_ai_api_def_service_proto_goTypes = nil
	file_kk_etcd_api_hub_ai_api_def_service_proto_depIdxs = nil
}
