Port: 2333
DebugMode: false
# RootPassword is the password of root user in etcd
#  if you didn't enable etcd auth, the password will be root user's password and enable auth
RootPassword: root
Etcd:
  Endpoints:
    - http://etcd-rel:2379
#    - http://127.0.0.1:2379
# not use now todo https://github.com/etcd-io/etcd/pull/16803
JWT:
  Key: You are re on your way to prison
  # minute
  ExpireTime: 1440

AI:
  Enable: false
  LLMModel: qwen2.5:0.5b
  # default: http://127.0.0.1:11434
  OllamaService: http://127.0.0.1:11434

MCPServer:
  Enable: false
  Port: 2444