// Code generated by kk_etcd_go. DO NOT EDIT.

package api_impl

import (
	"context"

	"gitee.com/cruvie/kk_go_kit/kk_grpc"
	"github.com/cruvie/kk_etcd_go/internal/service_hub/role/api_def"
	"github.com/cruvie/kk_etcd_go/internal/utils/internal_client"
)

type CServer struct {
	api_def.UnimplementedRoleServer
	ins server
}

func (x *CServer) RoleAdd(ctx context.Context, input *api_def.RoleAdd_Input) (*api_def.RoleAdd_Output, error) {
	ctx = kk_grpc.SetGrpcStage(ctx, internal_client.GlobalStage)
	return x.ins.RoleAdd(ctx, input)
}

func (x *CServer) RoleDelete(ctx context.Context, input *api_def.RoleDelete_Input) (*api_def.RoleDelete_Output, error) {
	ctx = kk_grpc.SetGrpcStage(ctx, internal_client.GlobalStage)
	return x.ins.RoleDelete(ctx, input)
}

func (x *CServer) RoleGet(ctx context.Context, input *api_def.RoleGet_Input) (*api_def.RoleGet_Output, error) {
	ctx = kk_grpc.SetGrpcStage(ctx, internal_client.GlobalStage)
	return x.ins.RoleGet(ctx, input)
}

func (x *CServer) RoleGrantPermission(ctx context.Context, input *api_def.RoleGrantPermission_Input) (*api_def.RoleGrantPermission_Output, error) {
	ctx = kk_grpc.SetGrpcStage(ctx, internal_client.GlobalStage)
	return x.ins.RoleGrantPermission(ctx, input)
}

func (x *CServer) RoleList(ctx context.Context, input *api_def.RoleList_Input) (*api_def.RoleList_Output, error) {
	ctx = kk_grpc.SetGrpcStage(ctx, internal_client.GlobalStage)
	return x.ins.RoleList(ctx, input)
}

func (x *CServer) RoleRevokePermission(ctx context.Context, input *api_def.RoleRevokePermission_Input) (*api_def.RoleRevokePermission_Output, error) {
	ctx = kk_grpc.SetGrpcStage(ctx, internal_client.GlobalStage)
	return x.ins.RoleRevokePermission(ctx, input)
}
