// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: internal/service_hub/user/api_def/service.proto

package api_def

import (
	_ "gitee.com/cruvie/kk_go_kit/kk_protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_internal_service_hub_user_api_def_service_proto protoreflect.FileDescriptor

const file_internal_service_hub_user_api_def_service_proto_rawDesc = "" +
	"\n" +
	"/internal/service_hub/user/api_def/service.proto\x12\akk_etcd\x1a/internal/service_hub/user/api_def/GetUser.proto\x1a-internal/service_hub/user/api_def/Login.proto\x1a.internal/service_hub/user/api_def/Logout.proto\x1a.internal/service_hub/user/api_def/MyInfo.proto\x1a/internal/service_hub/user/api_def/UserAdd.proto\x1a2internal/service_hub/user/api_def/UserDelete.proto\x1a5internal/service_hub/user/api_def/UserGrantRole.proto\x1a0internal/service_hub/user/api_def/UserList.proto\x1aAvendor/gitee.com/cruvie/kk_go_kit/kk_protobuf/extend_method.proto2\xab\x04\n" +
	"\x04User\x12A\n" +
	"\aGetUser\x12\x16.kk_etcd.GetUser.Input\x1a\x17.kk_etcd.GetUser.Output\"\x05\x8a\xa6\x1d\x01\x01\x126\n" +
	"\x05Login\x12\x14.kk_etcd.Login.Input\x1a\x15.kk_etcd.Login.Output\"\x00\x12>\n" +
	"\x06Logout\x12\x15.kk_etcd.Logout.Input\x1a\x16.kk_etcd.Logout.Output\"\x05\x8a\xa6\x1d\x01\x01\x12>\n" +
	"\x06MyInfo\x12\x15.kk_etcd.MyInfo.Input\x1a\x16.kk_etcd.MyInfo.Output\"\x05\x8a\xa6\x1d\x01\x01\x12A\n" +
	"\aUserAdd\x12\x16.kk_etcd.UserAdd.Input\x1a\x17.kk_etcd.UserAdd.Output\"\x05\x8a\xa6\x1d\x01\x01\x12J\n" +
	"\n" +
	"UserDelete\x12\x19.kk_etcd.UserDelete.Input\x1a\x1a.kk_etcd.UserDelete.Output\"\x05\x8a\xa6\x1d\x01\x01\x12S\n" +
	"\rUserGrantRole\x12\x1c.kk_etcd.UserGrantRole.Input\x1a\x1d.kk_etcd.UserGrantRole.Output\"\x05\x8a\xa6\x1d\x01\x01\x12D\n" +
	"\bUserList\x12\x17.kk_etcd.UserList.Input\x1a\x18.kk_etcd.UserList.Output\"\x05\x8a\xa6\x1d\x01\x01B\n" +
	"Z\b/api_defb\x06proto3"

var file_internal_service_hub_user_api_def_service_proto_goTypes = []any{
	(*GetUser_Input)(nil),        // 0: kk_etcd.GetUser.Input
	(*Login_Input)(nil),          // 1: kk_etcd.Login.Input
	(*Logout_Input)(nil),         // 2: kk_etcd.Logout.Input
	(*MyInfo_Input)(nil),         // 3: kk_etcd.MyInfo.Input
	(*UserAdd_Input)(nil),        // 4: kk_etcd.UserAdd.Input
	(*UserDelete_Input)(nil),     // 5: kk_etcd.UserDelete.Input
	(*UserGrantRole_Input)(nil),  // 6: kk_etcd.UserGrantRole.Input
	(*UserList_Input)(nil),       // 7: kk_etcd.UserList.Input
	(*GetUser_Output)(nil),       // 8: kk_etcd.GetUser.Output
	(*Login_Output)(nil),         // 9: kk_etcd.Login.Output
	(*Logout_Output)(nil),        // 10: kk_etcd.Logout.Output
	(*MyInfo_Output)(nil),        // 11: kk_etcd.MyInfo.Output
	(*UserAdd_Output)(nil),       // 12: kk_etcd.UserAdd.Output
	(*UserDelete_Output)(nil),    // 13: kk_etcd.UserDelete.Output
	(*UserGrantRole_Output)(nil), // 14: kk_etcd.UserGrantRole.Output
	(*UserList_Output)(nil),      // 15: kk_etcd.UserList.Output
}
var file_internal_service_hub_user_api_def_service_proto_depIdxs = []int32{
	0,  // 0: kk_etcd.User.GetUser:input_type -> kk_etcd.GetUser.Input
	1,  // 1: kk_etcd.User.Login:input_type -> kk_etcd.Login.Input
	2,  // 2: kk_etcd.User.Logout:input_type -> kk_etcd.Logout.Input
	3,  // 3: kk_etcd.User.MyInfo:input_type -> kk_etcd.MyInfo.Input
	4,  // 4: kk_etcd.User.UserAdd:input_type -> kk_etcd.UserAdd.Input
	5,  // 5: kk_etcd.User.UserDelete:input_type -> kk_etcd.UserDelete.Input
	6,  // 6: kk_etcd.User.UserGrantRole:input_type -> kk_etcd.UserGrantRole.Input
	7,  // 7: kk_etcd.User.UserList:input_type -> kk_etcd.UserList.Input
	8,  // 8: kk_etcd.User.GetUser:output_type -> kk_etcd.GetUser.Output
	9,  // 9: kk_etcd.User.Login:output_type -> kk_etcd.Login.Output
	10, // 10: kk_etcd.User.Logout:output_type -> kk_etcd.Logout.Output
	11, // 11: kk_etcd.User.MyInfo:output_type -> kk_etcd.MyInfo.Output
	12, // 12: kk_etcd.User.UserAdd:output_type -> kk_etcd.UserAdd.Output
	13, // 13: kk_etcd.User.UserDelete:output_type -> kk_etcd.UserDelete.Output
	14, // 14: kk_etcd.User.UserGrantRole:output_type -> kk_etcd.UserGrantRole.Output
	15, // 15: kk_etcd.User.UserList:output_type -> kk_etcd.UserList.Output
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_internal_service_hub_user_api_def_service_proto_init() }
func file_internal_service_hub_user_api_def_service_proto_init() {
	if File_internal_service_hub_user_api_def_service_proto != nil {
		return
	}
	file_internal_service_hub_user_api_def_GetUser_proto_init()
	file_internal_service_hub_user_api_def_Login_proto_init()
	file_internal_service_hub_user_api_def_Logout_proto_init()
	file_internal_service_hub_user_api_def_MyInfo_proto_init()
	file_internal_service_hub_user_api_def_UserAdd_proto_init()
	file_internal_service_hub_user_api_def_UserDelete_proto_init()
	file_internal_service_hub_user_api_def_UserGrantRole_proto_init()
	file_internal_service_hub_user_api_def_UserList_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_service_hub_user_api_def_service_proto_rawDesc), len(file_internal_service_hub_user_api_def_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_service_hub_user_api_def_service_proto_goTypes,
		DependencyIndexes: file_internal_service_hub_user_api_def_service_proto_depIdxs,
	}.Build()
	File_internal_service_hub_user_api_def_service_proto = out.File
	file_internal_service_hub_user_api_def_service_proto_goTypes = nil
	file_internal_service_hub_user_api_def_service_proto_depIdxs = nil
}
