// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: internal/service_hub/user/api_def/service.proto

package api_def

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_internal_service_hub_user_api_def_service_proto protoreflect.FileDescriptor

const file_internal_service_hub_user_api_def_service_proto_rawDesc = "" +
	"\n" +
	"/internal/service_hub/user/api_def/service.proto\x12\aapi_def\x1a/internal/service_hub/user/api_def/GetUser.proto\x1a-internal/service_hub/user/api_def/Login.proto\x1a.internal/service_hub/user/api_def/Logout.proto\x1a.internal/service_hub/user/api_def/MyInfo.proto\x1a/internal/service_hub/user/api_def/UserAdd.proto\x1a2internal/service_hub/user/api_def/UserDelete.proto\x1a5internal/service_hub/user/api_def/UserGrantRole.proto\x1a0internal/service_hub/user/api_def/UserList.proto2\xf8\x03\n" +
	"\x04User\x12:\n" +
	"\aGetUser\x12\x16.api_def.GetUser.Input\x1a\x17.api_def.GetUser.Output\x124\n" +
	"\x05Login\x12\x14.api_def.Login.Input\x1a\x15.api_def.Login.Output\x127\n" +
	"\x06Logout\x12\x15.api_def.Logout.Input\x1a\x16.api_def.Logout.Output\x127\n" +
	"\x06MyInfo\x12\x15.api_def.MyInfo.Input\x1a\x16.api_def.MyInfo.Output\x12:\n" +
	"\aUserAdd\x12\x16.api_def.UserAdd.Input\x1a\x17.api_def.UserAdd.Output\x12C\n" +
	"\n" +
	"UserDelete\x12\x19.api_def.UserDelete.Input\x1a\x1a.api_def.UserDelete.Output\x12L\n" +
	"\rUserGrantRole\x12\x1c.api_def.UserGrantRole.Input\x1a\x1d.api_def.UserGrantRole.Output\x12=\n" +
	"\bUserList\x12\x17.api_def.UserList.Input\x1a\x18.api_def.UserList.OutputB\n" +
	"Z\b/api_defb\x06proto3"

var file_internal_service_hub_user_api_def_service_proto_goTypes = []any{
	(*GetUser_Input)(nil),        // 0: api_def.GetUser.Input
	(*Login_Input)(nil),          // 1: api_def.Login.Input
	(*Logout_Input)(nil),         // 2: api_def.Logout.Input
	(*MyInfo_Input)(nil),         // 3: api_def.MyInfo.Input
	(*UserAdd_Input)(nil),        // 4: api_def.UserAdd.Input
	(*UserDelete_Input)(nil),     // 5: api_def.UserDelete.Input
	(*UserGrantRole_Input)(nil),  // 6: api_def.UserGrantRole.Input
	(*UserList_Input)(nil),       // 7: api_def.UserList.Input
	(*GetUser_Output)(nil),       // 8: api_def.GetUser.Output
	(*Login_Output)(nil),         // 9: api_def.Login.Output
	(*Logout_Output)(nil),        // 10: api_def.Logout.Output
	(*MyInfo_Output)(nil),        // 11: api_def.MyInfo.Output
	(*UserAdd_Output)(nil),       // 12: api_def.UserAdd.Output
	(*UserDelete_Output)(nil),    // 13: api_def.UserDelete.Output
	(*UserGrantRole_Output)(nil), // 14: api_def.UserGrantRole.Output
	(*UserList_Output)(nil),      // 15: api_def.UserList.Output
}
var file_internal_service_hub_user_api_def_service_proto_depIdxs = []int32{
	0,  // 0: api_def.User.GetUser:input_type -> api_def.GetUser.Input
	1,  // 1: api_def.User.Login:input_type -> api_def.Login.Input
	2,  // 2: api_def.User.Logout:input_type -> api_def.Logout.Input
	3,  // 3: api_def.User.MyInfo:input_type -> api_def.MyInfo.Input
	4,  // 4: api_def.User.UserAdd:input_type -> api_def.UserAdd.Input
	5,  // 5: api_def.User.UserDelete:input_type -> api_def.UserDelete.Input
	6,  // 6: api_def.User.UserGrantRole:input_type -> api_def.UserGrantRole.Input
	7,  // 7: api_def.User.UserList:input_type -> api_def.UserList.Input
	8,  // 8: api_def.User.GetUser:output_type -> api_def.GetUser.Output
	9,  // 9: api_def.User.Login:output_type -> api_def.Login.Output
	10, // 10: api_def.User.Logout:output_type -> api_def.Logout.Output
	11, // 11: api_def.User.MyInfo:output_type -> api_def.MyInfo.Output
	12, // 12: api_def.User.UserAdd:output_type -> api_def.UserAdd.Output
	13, // 13: api_def.User.UserDelete:output_type -> api_def.UserDelete.Output
	14, // 14: api_def.User.UserGrantRole:output_type -> api_def.UserGrantRole.Output
	15, // 15: api_def.User.UserList:output_type -> api_def.UserList.Output
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_internal_service_hub_user_api_def_service_proto_init() }
func file_internal_service_hub_user_api_def_service_proto_init() {
	if File_internal_service_hub_user_api_def_service_proto != nil {
		return
	}
	file_internal_service_hub_user_api_def_GetUser_proto_init()
	file_internal_service_hub_user_api_def_Login_proto_init()
	file_internal_service_hub_user_api_def_Logout_proto_init()
	file_internal_service_hub_user_api_def_MyInfo_proto_init()
	file_internal_service_hub_user_api_def_UserAdd_proto_init()
	file_internal_service_hub_user_api_def_UserDelete_proto_init()
	file_internal_service_hub_user_api_def_UserGrantRole_proto_init()
	file_internal_service_hub_user_api_def_UserList_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_service_hub_user_api_def_service_proto_rawDesc), len(file_internal_service_hub_user_api_def_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_service_hub_user_api_def_service_proto_goTypes,
		DependencyIndexes: file_internal_service_hub_user_api_def_service_proto_depIdxs,
	}.Build()
	File_internal_service_hub_user_api_def_service_proto = out.File
	file_internal_service_hub_user_api_def_service_proto_goTypes = nil
	file_internal_service_hub_user_api_def_service_proto_depIdxs = nil
}
