// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://kk_etcd_go/terms/",
        "contact": {
            "name": "kk_etcd_go",
            "url": "http://kk_etcd_go/support",
            "email": "kk_etcd_go@qq.com"
        },
        "license": {
            "name": "Secret",
            "url": "http://kk_etcd_go/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ai/query": {
            "post": {
                "description": "query ai",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "ai"
                ],
                "operationId": "Query",
                "parameters": [
                    {
                        "description": "Query_Input",
                        "name": "Query_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_ai_query.Query_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_ai_query.Query_Output"
                        }
                    }
                }
            }
        },
        "/backup/allKVsBackup": {
            "post": {
                "description": "all kvs backup",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "backup"
                ],
                "operationId": "AllKVsBackup",
                "parameters": [
                    {
                        "description": "AllKVsBackup_Input",
                        "name": "AllKVsBackup_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_backup_allKVsBackup.AllKVsBackup_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_backup_allKVsBackup.AllKVsBackup_Output"
                        }
                    }
                }
            }
        },
        "/backup/allKVsRestore": {
            "post": {
                "description": "all kvs restore",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "backup"
                ],
                "operationId": "AllKVsRestore",
                "parameters": [
                    {
                        "description": "AllKVsRestore_Input",
                        "name": "AllKVsRestore_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_backup_allKVsRestore.AllKVsRestore_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_backup_allKVsRestore.AllKVsRestore_Output"
                        }
                    }
                }
            }
        },
        "/backup/snapshot": {
            "post": {
                "description": "snapshot",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "backup"
                ],
                "operationId": "Snapshot",
                "parameters": [
                    {
                        "description": "Snapshot_Input",
                        "name": "Snapshot_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_backup_snapshot.Snapshot_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_backup_snapshot.Snapshot_Output"
                        }
                    }
                }
            }
        },
        "/backup/snapshotInfo": {
            "post": {
                "description": "snapshot info",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "backup"
                ],
                "operationId": "SnapshotInfo",
                "parameters": [
                    {
                        "description": "SnapshotInfo_Input",
                        "name": "SnapshotInfo_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_backup_snapshotInfo.SnapshotInfo_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_backup_snapshotInfo.SnapshotInfo_Output"
                        }
                    }
                }
            }
        },
        "/backup/snapshotRestore": {
            "post": {
                "description": "snapshot restore",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "backup"
                ],
                "operationId": "SnapshotRestore",
                "parameters": [
                    {
                        "description": "SnapshotRestore_Input",
                        "name": "SnapshotRestore_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_backup_snapshotRestore.SnapshotRestore_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_backup_snapshotRestore.SnapshotRestore_Output"
                        }
                    }
                }
            }
        },
        "/kv/kVDel": {
            "post": {
                "description": "del kv",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "kv"
                ],
                "operationId": "KVDel",
                "parameters": [
                    {
                        "description": "KVDel_Input",
                        "name": "KVDel_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_kv_kVDel.KVDel_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_kv_kVDel.KVDel_Output"
                        }
                    }
                }
            }
        },
        "/kv/kVGet": {
            "post": {
                "description": "get kv",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "kv"
                ],
                "operationId": "KVGet",
                "parameters": [
                    {
                        "description": "KVGet_Input",
                        "name": "KVGet_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_kv_kVGet.KVGet_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_kv_kVGet.KVGet_Output"
                        }
                    }
                }
            }
        },
        "/kv/kVList": {
            "post": {
                "description": "list kv",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "kv"
                ],
                "operationId": "KVList",
                "parameters": [
                    {
                        "description": "KVList_Input",
                        "name": "KVList_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_kv_kVList.KVList_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_kv_kVList.KVList_Output"
                        }
                    }
                }
            }
        },
        "/kv/kVPut": {
            "post": {
                "description": "put kv",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "kv"
                ],
                "operationId": "KVPut",
                "parameters": [
                    {
                        "description": "KVPut_Input",
                        "name": "KVPut_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_kv_kVPut.KVPut_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_kv_kVPut.KVPut_Output"
                        }
                    }
                }
            }
        },
        "/role/roleAdd": {
            "post": {
                "description": "add role",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "role"
                ],
                "operationId": "RoleAdd",
                "parameters": [
                    {
                        "description": "RoleAdd_Input",
                        "name": "RoleAdd_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_role_roleAdd.RoleAdd_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_role_roleAdd.RoleAdd_Output"
                        }
                    }
                }
            }
        },
        "/role/roleDelete": {
            "post": {
                "description": "delete role",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "role"
                ],
                "operationId": "RoleDelete",
                "parameters": [
                    {
                        "description": "RoleDelete_Input",
                        "name": "RoleDelete_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_role_roleDelete.RoleDelete_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_role_roleDelete.RoleDelete_Output"
                        }
                    }
                }
            }
        },
        "/role/roleGet": {
            "post": {
                "description": "get role",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "role"
                ],
                "operationId": "RoleGet",
                "parameters": [
                    {
                        "description": "RoleGet_Input",
                        "name": "RoleGet_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_role_roleGet.RoleGet_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_role_roleGet.RoleGet_Output"
                        }
                    }
                }
            }
        },
        "/role/roleGrantPermission": {
            "post": {
                "description": "grant permission",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "role"
                ],
                "operationId": "RoleGrantPermission",
                "parameters": [
                    {
                        "description": "RoleGrantPermission_Input",
                        "name": "RoleGrantPermission_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_role_roleGrantPermission.RoleGrantPermission_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_role_roleGrantPermission.RoleGrantPermission_Output"
                        }
                    }
                }
            }
        },
        "/role/roleList": {
            "post": {
                "description": "list role",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "role"
                ],
                "operationId": "RoleList",
                "parameters": [
                    {
                        "description": "RoleList_Input",
                        "name": "RoleList_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_role_roleList.RoleList_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_role_roleList.RoleList_Output"
                        }
                    }
                }
            }
        },
        "/role/roleRevokePermission": {
            "post": {
                "description": "revoke permission",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "role"
                ],
                "operationId": "RoleRevokePermission",
                "parameters": [
                    {
                        "description": "RoleRevokePermission_Input",
                        "name": "RoleRevokePermission_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_role_roleRevokePermission.RoleRevokePermission_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_role_roleRevokePermission.RoleRevokePermission_Output"
                        }
                    }
                }
            }
        },
        "/server/deregisterServer": {
            "post": {
                "description": "deregister server",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "server"
                ],
                "operationId": "DeregisterServer",
                "parameters": [
                    {
                        "description": "DeregisterServer_Input",
                        "name": "DeregisterServer_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_server_deregisterServer.DeregisterServer_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_server_deregisterServer.DeregisterServer_Output"
                        }
                    }
                }
            }
        },
        "/server/serverList": {
            "post": {
                "description": "list server",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "server"
                ],
                "operationId": "ServerList",
                "parameters": [
                    {
                        "description": "ServerList_Input",
                        "name": "ServerList_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_server_serverList.ServerList_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_server_serverList.ServerList_Output"
                        }
                    }
                }
            }
        },
        "/user/getUser": {
            "post": {
                "description": "get user",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "user"
                ],
                "operationId": "GetUser",
                "parameters": [
                    {
                        "description": "GetUser_Input",
                        "name": "GetUser_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_user_getUser.GetUser_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_user_getUser.GetUser_Output"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "login",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "user"
                ],
                "operationId": "Login",
                "parameters": [
                    {
                        "description": "Login_Input",
                        "name": "Login_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_user_login.Login_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_user_login.Login_Output"
                        }
                    }
                }
            }
        },
        "/user/logout": {
            "post": {
                "description": "logout",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "user"
                ],
                "operationId": "Logout",
                "parameters": [
                    {
                        "description": "Logout_Input",
                        "name": "Logout_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_user_logout.Logout_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_user_logout.Logout_Output"
                        }
                    }
                }
            }
        },
        "/user/myInfo": {
            "post": {
                "description": "get my info",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "user"
                ],
                "operationId": "MyInfo",
                "parameters": [
                    {
                        "description": "MyInfo_Input",
                        "name": "MyInfo_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_user_myInfo.MyInfo_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_user_myInfo.MyInfo_Output"
                        }
                    }
                }
            }
        },
        "/user/userAdd": {
            "post": {
                "description": "add user",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "user"
                ],
                "operationId": "UserAdd",
                "parameters": [
                    {
                        "description": "UserAdd_Input",
                        "name": "UserAdd_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_user_userAdd.UserAdd_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_user_userAdd.UserAdd_Output"
                        }
                    }
                }
            }
        },
        "/user/userDelete": {
            "post": {
                "description": "delete user",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "user"
                ],
                "operationId": "UserDelete",
                "parameters": [
                    {
                        "description": "UserDelete_Input",
                        "name": "UserDelete_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_user_userDelete.UserDelete_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_user_userDelete.UserDelete_Output"
                        }
                    }
                }
            }
        },
        "/user/userGrantRole": {
            "post": {
                "description": "grant role",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "user"
                ],
                "operationId": "UserGrantRole",
                "parameters": [
                    {
                        "description": "UserGrantRole_Input",
                        "name": "UserGrantRole_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_user_userGrantRole.UserGrantRole_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_user_userGrantRole.UserGrantRole_Output"
                        }
                    }
                }
            }
        },
        "/user/userList": {
            "post": {
                "description": "list user",
                "consumes": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "produces": [
                    "application/json",
                    "application/x-protobuf"
                ],
                "tags": [
                    "user"
                ],
                "operationId": "UserList",
                "parameters": [
                    {
                        "description": "UserList_Input",
                        "name": "UserList_Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_user_userList.UserList_Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mgr_hub_mgr_user_userList.UserList_Output"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_mgr_hub_mgr_ai_query.Query_Input": {
            "type": "object",
            "properties": {
                "Question": {
                    "type": "string"
                }
            }
        },
        "internal_mgr_hub_mgr_ai_query.Query_Output": {
            "type": "object",
            "properties": {
                "Answer": {
                    "type": "string"
                }
            }
        },
        "internal_mgr_hub_mgr_backup_allKVsBackup.AllKVsBackup_Input": {
            "type": "object"
        },
        "internal_mgr_hub_mgr_backup_allKVsBackup.AllKVsBackup_Output": {
            "type": "object",
            "properties": {
                "File": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "Name": {
                    "type": "string"
                }
            }
        },
        "internal_mgr_hub_mgr_backup_allKVsRestore.AllKVsRestore_Input": {
            "type": "object",
            "properties": {
                "File": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "internal_mgr_hub_mgr_backup_allKVsRestore.AllKVsRestore_Output": {
            "type": "object"
        },
        "internal_mgr_hub_mgr_backup_snapshot.Snapshot_Input": {
            "type": "object"
        },
        "internal_mgr_hub_mgr_backup_snapshot.Snapshot_Output": {
            "type": "object",
            "properties": {
                "File": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "Name": {
                    "type": "string"
                }
            }
        },
        "internal_mgr_hub_mgr_backup_snapshotInfo.SnapshotInfo_Input": {
            "type": "object",
            "properties": {
                "File": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "internal_mgr_hub_mgr_backup_snapshotInfo.SnapshotInfo_Output": {
            "type": "object",
            "properties": {
                "Info": {
                    "type": "string"
                }
            }
        },
        "internal_mgr_hub_mgr_backup_snapshotRestore.SnapshotRestore_Input": {
            "type": "object"
        },
        "internal_mgr_hub_mgr_backup_snapshotRestore.SnapshotRestore_Output": {
            "type": "object",
            "properties": {
                "CmdStr": {
                    "type": "string"
                }
            }
        },
        "internal_mgr_hub_mgr_kv_kVDel.KVDel_Input": {
            "type": "object",
            "properties": {
                "Key": {
                    "type": "string"
                }
            }
        },
        "internal_mgr_hub_mgr_kv_kVDel.KVDel_Output": {
            "type": "object"
        },
        "internal_mgr_hub_mgr_kv_kVGet.KVGet_Input": {
            "type": "object",
            "properties": {
                "Key": {
                    "type": "string"
                }
            }
        },
        "internal_mgr_hub_mgr_kv_kVGet.KVGet_Output": {
            "type": "object",
            "properties": {
                "KV": {
                    "$ref": "#/definitions/kk_etcd_models.PBKV"
                }
            }
        },
        "internal_mgr_hub_mgr_kv_kVList.KVList_Input": {
            "type": "object",
            "properties": {
                "Prefix": {
                    "type": "string"
                }
            }
        },
        "internal_mgr_hub_mgr_kv_kVList.KVList_Output": {
            "type": "object",
            "properties": {
                "KVList": {
                    "$ref": "#/definitions/kk_etcd_models.PBListKV"
                }
            }
        },
        "internal_mgr_hub_mgr_kv_kVPut.KVPut_Input": {
            "type": "object",
            "properties": {
                "Key": {
                    "type": "string"
                },
                "Value": {
                    "type": "string"
                }
            }
        },
        "internal_mgr_hub_mgr_kv_kVPut.KVPut_Output": {
            "type": "object"
        },
        "internal_mgr_hub_mgr_role_roleAdd.RoleAdd_Input": {
            "type": "object",
            "properties": {
                "Name": {
                    "type": "string"
                }
            }
        },
        "internal_mgr_hub_mgr_role_roleAdd.RoleAdd_Output": {
            "type": "object"
        },
        "internal_mgr_hub_mgr_role_roleDelete.RoleDelete_Input": {
            "type": "object",
            "properties": {
                "Name": {
                    "type": "string"
                }
            }
        },
        "internal_mgr_hub_mgr_role_roleDelete.RoleDelete_Output": {
            "type": "object"
        },
        "internal_mgr_hub_mgr_role_roleGet.RoleGet_Input": {
            "type": "object",
            "properties": {
                "Name": {
                    "type": "string"
                }
            }
        },
        "internal_mgr_hub_mgr_role_roleGet.RoleGet_Output": {
            "type": "object",
            "properties": {
                "Role": {
                    "$ref": "#/definitions/kk_etcd_models.PBRole"
                }
            }
        },
        "internal_mgr_hub_mgr_role_roleGrantPermission.RoleGrantPermission_Input": {
            "type": "object",
            "properties": {
                "Name": {
                    "type": "string"
                },
                "Perm": {
                    "$ref": "#/definitions/kk_etcd_models.PBPermission"
                }
            }
        },
        "internal_mgr_hub_mgr_role_roleGrantPermission.RoleGrantPermission_Output": {
            "type": "object"
        },
        "internal_mgr_hub_mgr_role_roleList.RoleList_Input": {
            "type": "object"
        },
        "internal_mgr_hub_mgr_role_roleList.RoleList_Output": {
            "type": "object",
            "properties": {
                "ListRole": {
                    "$ref": "#/definitions/kk_etcd_models.PBListRole"
                }
            }
        },
        "internal_mgr_hub_mgr_role_roleRevokePermission.RoleRevokePermission_Input": {
            "type": "object",
            "properties": {
                "Key": {
                    "type": "string"
                },
                "Name": {
                    "type": "string"
                },
                "RangeEnd": {
                    "type": "string"
                }
            }
        },
        "internal_mgr_hub_mgr_role_roleRevokePermission.RoleRevokePermission_Output": {
            "type": "object"
        },
        "internal_mgr_hub_mgr_server_deregisterServer.DeregisterServer_Input": {
            "type": "object",
            "properties": {
                "Server": {
                    "$ref": "#/definitions/kk_etcd_models.PBServer"
                }
            }
        },
        "internal_mgr_hub_mgr_server_deregisterServer.DeregisterServer_Output": {
            "type": "object"
        },
        "internal_mgr_hub_mgr_server_serverList.ServerList_Input": {
            "type": "object",
            "properties": {
                "ServerName": {
                    "type": "string"
                },
                "ServerType": {
                    "type": "string"
                }
            }
        },
        "internal_mgr_hub_mgr_server_serverList.ServerList_Output": {
            "type": "object",
            "properties": {
                "ServerList": {
                    "$ref": "#/definitions/kk_etcd_models.PBListServer"
                }
            }
        },
        "internal_mgr_hub_mgr_user_getUser.GetUser_Input": {
            "type": "object",
            "properties": {
                "UserName": {
                    "type": "string"
                }
            }
        },
        "internal_mgr_hub_mgr_user_getUser.GetUser_Output": {
            "type": "object",
            "properties": {
                "User": {
                    "$ref": "#/definitions/kk_etcd_models.PBUser"
                }
            }
        },
        "internal_mgr_hub_mgr_user_login.Login_Input": {
            "type": "object",
            "properties": {
                "Password": {
                    "type": "string"
                },
                "UserName": {
                    "type": "string"
                }
            }
        },
        "internal_mgr_hub_mgr_user_login.Login_Output": {
            "type": "object",
            "properties": {
                "Token": {
                    "type": "string"
                }
            }
        },
        "internal_mgr_hub_mgr_user_logout.Logout_Input": {
            "type": "object"
        },
        "internal_mgr_hub_mgr_user_logout.Logout_Output": {
            "type": "object"
        },
        "internal_mgr_hub_mgr_user_myInfo.MyInfo_Input": {
            "type": "object"
        },
        "internal_mgr_hub_mgr_user_myInfo.MyInfo_Output": {
            "type": "object",
            "properties": {
                "Roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "UserName": {
                    "type": "string"
                }
            }
        },
        "internal_mgr_hub_mgr_user_userAdd.UserAdd_Input": {
            "type": "object",
            "properties": {
                "Password": {
                    "type": "string"
                },
                "Roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "UserName": {
                    "type": "string"
                }
            }
        },
        "internal_mgr_hub_mgr_user_userAdd.UserAdd_Output": {
            "type": "object"
        },
        "internal_mgr_hub_mgr_user_userDelete.UserDelete_Input": {
            "type": "object",
            "properties": {
                "UserName": {
                    "type": "string"
                }
            }
        },
        "internal_mgr_hub_mgr_user_userDelete.UserDelete_Output": {
            "type": "object"
        },
        "internal_mgr_hub_mgr_user_userGrantRole.UserGrantRole_Input": {
            "type": "object",
            "properties": {
                "Roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "UserName": {
                    "type": "string"
                }
            }
        },
        "internal_mgr_hub_mgr_user_userGrantRole.UserGrantRole_Output": {
            "type": "object"
        },
        "internal_mgr_hub_mgr_user_userList.UserList_Input": {
            "type": "object"
        },
        "internal_mgr_hub_mgr_user_userList.UserList_Output": {
            "type": "object",
            "properties": {
                "ListUser": {
                    "$ref": "#/definitions/kk_etcd_models.PBListUser"
                }
            }
        },
        "kk_etcd_models.PBKV": {
            "type": "object",
            "properties": {
                "Key": {
                    "type": "string"
                },
                "Value": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.PBListKV": {
            "type": "object",
            "properties": {
                "ListKV": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/kk_etcd_models.PBKV"
                    }
                }
            }
        },
        "kk_etcd_models.PBListRole": {
            "type": "object",
            "properties": {
                "List": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/kk_etcd_models.PBRole"
                    }
                }
            }
        },
        "kk_etcd_models.PBListServer": {
            "type": "object",
            "properties": {
                "ListServer": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/kk_etcd_models.PBServer"
                    }
                }
            }
        },
        "kk_etcd_models.PBListUser": {
            "type": "object",
            "properties": {
                "ListUser": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/kk_etcd_models.PBUser"
                    }
                }
            }
        },
        "kk_etcd_models.PBPermission": {
            "type": "object",
            "properties": {
                "Key": {
                    "type": "string"
                },
                "PermissionType": {
                    "description": "authpb.READ 0\nauthpb.WRITE 1\nauthpb.READWRITE 2",
                    "type": "integer"
                },
                "RangeEnd": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.PBRole": {
            "type": "object",
            "properties": {
                "Name": {
                    "type": "string"
                },
                "Perms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/kk_etcd_models.PBPermission"
                    }
                }
            }
        },
        "kk_etcd_models.PBServer": {
            "type": "object",
            "properties": {
                "EndpointAddr": {
                    "type": "string"
                },
                "EndpointKey": {
                    "type": "string"
                },
                "LastCheck": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "Msg": {
                    "type": "string"
                },
                "ServerType": {
                    "type": "string"
                },
                "Status": {
                    "$ref": "#/definitions/kk_etcd_models.PBServer_ServerStatus"
                }
            }
        },
        "kk_etcd_models.PBServer_ServerStatus": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "PBServer_UnKnown",
                "PBServer_Running",
                "PBServer_Stop",
                "PBServer_Init"
            ]
        },
        "kk_etcd_models.PBUser": {
            "type": "object",
            "properties": {
                "Password": {
                    "type": "string"
                },
                "Roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "UserName": {
                    "type": "string"
                }
            }
        },
        "timestamppb.Timestamp": {
            "type": "object",
            "properties": {
                "nanos": {
                    "description": "Non-negative fractions of a second at nanosecond resolution. Negative\nsecond values with fractions must still have non-negative nanos values\nthat count forward in time. Must be from 0 to 999,999,999\ninclusive.",
                    "type": "integer"
                },
                "seconds": {
                    "description": "Represents seconds of UTC time since Unix epoch\n1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to\n9999-12-31T23:59:59Z inclusive.",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.4.1",
	Host:             "localhost:2333",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "kk_etcd_go API",
	Description:      "kk_etcd_go terms.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
