// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://kk_etcd_go/terms/",
        "contact": {
            "name": "kk_etcd_go",
            "url": "http://kk_etcd_go/support",
            "email": "kk_etcd_go@qq.com"
        },
        "license": {
            "name": "Secret",
            "url": "http://kk_etcd_go/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/backup/allKVsBackup": {
            "post": {
                "description": "all kvs backup",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "backup"
                ],
                "parameters": [
                    {
                        "description": "AllKVsBackupParam",
                        "name": "AllKVsBackupParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.AllKVsBackupParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.AllKVsBackupResponse"
                        }
                    }
                }
            }
        },
        "/backup/allKVsRestore": {
            "post": {
                "description": "all kvs restore",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "backup"
                ],
                "parameters": [
                    {
                        "description": "AllKVsRestoreParam",
                        "name": "AllKVsRestoreParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.AllKVsRestoreParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.AllKVsRestoreResponse"
                        }
                    }
                }
            }
        },
        "/backup/snapshot": {
            "post": {
                "description": "snapshot",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "backup"
                ],
                "parameters": [
                    {
                        "description": "SnapshotParam",
                        "name": "SnapshotParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.SnapshotParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.SnapshotResponse"
                        }
                    }
                }
            }
        },
        "/backup/snapshotInfo": {
            "post": {
                "description": "snapshot info",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "backup"
                ],
                "parameters": [
                    {
                        "description": "SnapshotInfoParam",
                        "name": "SnapshotInfoParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.SnapshotInfoParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.SnapshotInfoResponse"
                        }
                    }
                }
            }
        },
        "/backup/snapshotRestore": {
            "post": {
                "description": "snapshot restore",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "backup"
                ],
                "parameters": [
                    {
                        "description": "SnapshotRestoreParam",
                        "name": "SnapshotRestoreParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.SnapshotRestoreParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.SnapshotRestoreResponse"
                        }
                    }
                }
            }
        },
        "/kv/kVDel": {
            "post": {
                "description": "del kv",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "kv"
                ],
                "parameters": [
                    {
                        "description": "KVDelParam",
                        "name": "KVDelParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.KVDelParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.KVDelResponse"
                        }
                    }
                }
            }
        },
        "/kv/kVGet": {
            "post": {
                "description": "get kv",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "kv"
                ],
                "parameters": [
                    {
                        "description": "KVGetParam",
                        "name": "KVGetParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.KVGetParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.KVGetResponse"
                        }
                    }
                }
            }
        },
        "/kv/kVList": {
            "post": {
                "description": "list kv",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "kv"
                ],
                "parameters": [
                    {
                        "description": "KVListParam",
                        "name": "KVListParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.KVListParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.KVListResponse"
                        }
                    }
                }
            }
        },
        "/kv/kVPut": {
            "post": {
                "description": "put kv",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "kv"
                ],
                "parameters": [
                    {
                        "description": "KVPutParam",
                        "name": "KVPutParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.KVPutParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.KVPutResponse"
                        }
                    }
                }
            }
        },
        "/role/roleAdd": {
            "post": {
                "description": "add role",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "role"
                ],
                "parameters": [
                    {
                        "description": "RoleAddParam",
                        "name": "RoleAddParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.RoleAddParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.RoleAddResponse"
                        }
                    }
                }
            }
        },
        "/role/roleDelete": {
            "post": {
                "description": "delete role",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "role"
                ],
                "parameters": [
                    {
                        "description": "RoleDeleteParam",
                        "name": "RoleDeleteParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.RoleDeleteParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.RoleDeleteResponse"
                        }
                    }
                }
            }
        },
        "/role/roleGet": {
            "post": {
                "description": "get role",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "role"
                ],
                "parameters": [
                    {
                        "description": "RoleGetParam",
                        "name": "RoleGetParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.RoleGetParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.RoleGetResponse"
                        }
                    }
                }
            }
        },
        "/role/roleGrantPermission": {
            "post": {
                "description": "grant permission",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "role"
                ],
                "parameters": [
                    {
                        "description": "RoleGrantPermissionParam",
                        "name": "RoleGrantPermissionParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.RoleGrantPermissionParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.RoleGrantPermissionResponse"
                        }
                    }
                }
            }
        },
        "/role/roleList": {
            "post": {
                "description": "list role",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "role"
                ],
                "parameters": [
                    {
                        "description": "RoleListParam",
                        "name": "RoleListParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.RoleListParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.RoleListResponse"
                        }
                    }
                }
            }
        },
        "/role/roleRevokePermission": {
            "post": {
                "description": "revoke permission",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "role"
                ],
                "parameters": [
                    {
                        "description": "RoleRevokePermissionParam",
                        "name": "RoleRevokePermissionParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.RoleRevokePermissionParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.RoleRevokePermissionResponse"
                        }
                    }
                }
            }
        },
        "/server/deregisterServer": {
            "post": {
                "description": "deregister server",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "server"
                ],
                "parameters": [
                    {
                        "description": "DeregisterServerParam",
                        "name": "DeregisterServerParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.DeregisterServerParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.DeregisterServerResponse"
                        }
                    }
                }
            }
        },
        "/server/serverList": {
            "post": {
                "description": "list server",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "server"
                ],
                "parameters": [
                    {
                        "description": "ServerListParam",
                        "name": "ServerListParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.ServerListParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.ServerListResponse"
                        }
                    }
                }
            }
        },
        "/user/getUser": {
            "post": {
                "description": "get user",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "description": "GetUserParam",
                        "name": "GetUserParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.GetUserParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.GetUserResponse"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "login",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "description": "LoginParam",
                        "name": "LoginParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.LoginParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.LoginResponse"
                        }
                    }
                }
            }
        },
        "/user/logout": {
            "post": {
                "description": "logout",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "description": "LogoutParam",
                        "name": "LogoutParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.LogoutParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.LogoutResponse"
                        }
                    }
                }
            }
        },
        "/user/myInfo": {
            "post": {
                "description": "get my info",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "description": "MyInfoParam",
                        "name": "MyInfoParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.MyInfoParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.MyInfoResponse"
                        }
                    }
                }
            }
        },
        "/user/userAdd": {
            "post": {
                "description": "add user",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "description": "UserAddParam",
                        "name": "UserAddParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.UserAddParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.UserAddResponse"
                        }
                    }
                }
            }
        },
        "/user/userDelete": {
            "post": {
                "description": "delete user",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "description": "UserDeleteParam",
                        "name": "UserDeleteParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.UserDeleteParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.UserDeleteResponse"
                        }
                    }
                }
            }
        },
        "/user/userGrantRole": {
            "post": {
                "description": "grant role",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "description": "UserGrantRoleParam",
                        "name": "UserGrantRoleParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.UserGrantRoleParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.UserGrantRoleResponse"
                        }
                    }
                }
            }
        },
        "/user/userList": {
            "post": {
                "description": "list user",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "description": "UserListParam",
                        "name": "UserListParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.UserListParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kk_etcd_models.UserListResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "kk_etcd_models.AllKVsBackupParam": {
            "type": "object"
        },
        "kk_etcd_models.AllKVsBackupResponse": {
            "type": "object",
            "properties": {
                "File": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "Name": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.AllKVsRestoreParam": {
            "type": "object",
            "properties": {
                "File": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "kk_etcd_models.AllKVsRestoreResponse": {
            "type": "object"
        },
        "kk_etcd_models.DeregisterServerParam": {
            "type": "object",
            "properties": {
                "Key": {
                    "description": "ServerType/ServerName/Addr",
                    "type": "string"
                },
                "Target": {
                    "description": "ServerType/ServerName",
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.DeregisterServerResponse": {
            "type": "object"
        },
        "kk_etcd_models.GetUserParam": {
            "type": "object",
            "properties": {
                "UserName": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.GetUserResponse": {
            "type": "object",
            "properties": {
                "User": {
                    "$ref": "#/definitions/kk_etcd_models.PBUser"
                }
            }
        },
        "kk_etcd_models.KVDelParam": {
            "type": "object",
            "properties": {
                "Key": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.KVDelResponse": {
            "type": "object"
        },
        "kk_etcd_models.KVGetParam": {
            "type": "object",
            "properties": {
                "Key": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.KVGetResponse": {
            "type": "object",
            "properties": {
                "KV": {
                    "$ref": "#/definitions/kk_etcd_models.PBKV"
                }
            }
        },
        "kk_etcd_models.KVListParam": {
            "type": "object",
            "properties": {
                "Prefix": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.KVListResponse": {
            "type": "object",
            "properties": {
                "KVList": {
                    "$ref": "#/definitions/kk_etcd_models.PBListKV"
                }
            }
        },
        "kk_etcd_models.KVPutParam": {
            "type": "object",
            "properties": {
                "Key": {
                    "type": "string"
                },
                "Value": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.KVPutResponse": {
            "type": "object"
        },
        "kk_etcd_models.LoginParam": {
            "type": "object",
            "properties": {
                "Password": {
                    "type": "string"
                },
                "UserName": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.LoginResponse": {
            "type": "object",
            "properties": {
                "Token": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.LogoutParam": {
            "type": "object"
        },
        "kk_etcd_models.LogoutResponse": {
            "type": "object"
        },
        "kk_etcd_models.MyInfoParam": {
            "type": "object"
        },
        "kk_etcd_models.MyInfoResponse": {
            "type": "object",
            "properties": {
                "Roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "UserName": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.PBKV": {
            "type": "object",
            "properties": {
                "Key": {
                    "type": "string"
                },
                "Value": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.PBListKV": {
            "type": "object",
            "properties": {
                "ListKV": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/kk_etcd_models.PBKV"
                    }
                }
            }
        },
        "kk_etcd_models.PBListRole": {
            "type": "object",
            "properties": {
                "List": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/kk_etcd_models.PBRole"
                    }
                }
            }
        },
        "kk_etcd_models.PBListServer": {
            "type": "object",
            "properties": {
                "ListServer": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/kk_etcd_models.PBServer"
                    }
                }
            }
        },
        "kk_etcd_models.PBListUser": {
            "type": "object",
            "properties": {
                "ListUser": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/kk_etcd_models.PBUser"
                    }
                }
            }
        },
        "kk_etcd_models.PBPermission": {
            "type": "object",
            "properties": {
                "Key": {
                    "type": "string"
                },
                "PermissionType": {
                    "description": "authpb.READ 0\nauthpb.WRITE 1\nauthpb.READWRITE 2",
                    "type": "integer"
                },
                "RangeEnd": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.PBRole": {
            "type": "object",
            "properties": {
                "Name": {
                    "type": "string"
                },
                "Perms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/kk_etcd_models.PBPermission"
                    }
                }
            }
        },
        "kk_etcd_models.PBServer": {
            "type": "object",
            "properties": {
                "LastCheck": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "Msg": {
                    "type": "string"
                },
                "ServerAddr": {
                    "type": "string"
                },
                "ServerName": {
                    "type": "string"
                },
                "Status": {
                    "$ref": "#/definitions/kk_etcd_models.PBServer_ServerStatus"
                }
            }
        },
        "kk_etcd_models.PBServer_ServerStatus": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "PBServer_UnKnown",
                "PBServer_Running",
                "PBServer_Stop",
                "PBServer_Init"
            ]
        },
        "kk_etcd_models.PBUser": {
            "type": "object",
            "properties": {
                "Password": {
                    "type": "string"
                },
                "Roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "UserName": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.RoleAddParam": {
            "type": "object",
            "properties": {
                "Name": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.RoleAddResponse": {
            "type": "object"
        },
        "kk_etcd_models.RoleDeleteParam": {
            "type": "object",
            "properties": {
                "Name": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.RoleDeleteResponse": {
            "type": "object"
        },
        "kk_etcd_models.RoleGetParam": {
            "type": "object",
            "properties": {
                "Name": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.RoleGetResponse": {
            "type": "object",
            "properties": {
                "Role": {
                    "$ref": "#/definitions/kk_etcd_models.PBRole"
                }
            }
        },
        "kk_etcd_models.RoleGrantPermissionParam": {
            "type": "object",
            "properties": {
                "Name": {
                    "type": "string"
                },
                "Perm": {
                    "$ref": "#/definitions/kk_etcd_models.PBPermission"
                }
            }
        },
        "kk_etcd_models.RoleGrantPermissionResponse": {
            "type": "object"
        },
        "kk_etcd_models.RoleListParam": {
            "type": "object"
        },
        "kk_etcd_models.RoleListResponse": {
            "type": "object",
            "properties": {
                "ListRole": {
                    "$ref": "#/definitions/kk_etcd_models.PBListRole"
                }
            }
        },
        "kk_etcd_models.RoleRevokePermissionParam": {
            "type": "object",
            "properties": {
                "Key": {
                    "type": "string"
                },
                "Name": {
                    "type": "string"
                },
                "RangeEnd": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.RoleRevokePermissionResponse": {
            "type": "object"
        },
        "kk_etcd_models.ServerListParam": {
            "type": "object",
            "properties": {
                "ServerName": {
                    "type": "string"
                },
                "ServerType": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.ServerListResponse": {
            "type": "object",
            "properties": {
                "ServerList": {
                    "$ref": "#/definitions/kk_etcd_models.PBListServer"
                }
            }
        },
        "kk_etcd_models.SnapshotInfoParam": {
            "type": "object",
            "properties": {
                "File": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "kk_etcd_models.SnapshotInfoResponse": {
            "type": "object",
            "properties": {
                "Info": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.SnapshotParam": {
            "type": "object"
        },
        "kk_etcd_models.SnapshotResponse": {
            "type": "object",
            "properties": {
                "File": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "Name": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.SnapshotRestoreParam": {
            "type": "object"
        },
        "kk_etcd_models.SnapshotRestoreResponse": {
            "type": "object",
            "properties": {
                "CmdStr": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.UserAddParam": {
            "type": "object",
            "properties": {
                "Password": {
                    "type": "string"
                },
                "Roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "UserName": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.UserAddResponse": {
            "type": "object"
        },
        "kk_etcd_models.UserDeleteParam": {
            "type": "object",
            "properties": {
                "UserName": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.UserDeleteResponse": {
            "type": "object"
        },
        "kk_etcd_models.UserGrantRoleParam": {
            "type": "object",
            "properties": {
                "Roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "UserName": {
                    "type": "string"
                }
            }
        },
        "kk_etcd_models.UserGrantRoleResponse": {
            "type": "object"
        },
        "kk_etcd_models.UserListParam": {
            "type": "object"
        },
        "kk_etcd_models.UserListResponse": {
            "type": "object",
            "properties": {
                "ListUser": {
                    "$ref": "#/definitions/kk_etcd_models.PBListUser"
                }
            }
        },
        "timestamppb.Timestamp": {
            "type": "object",
            "properties": {
                "nanos": {
                    "description": "Non-negative fractions of a second at nanosecond resolution. Negative\nsecond values with fractions must still have non-negative nanos values\nthat count forward in time. Must be from 0 to 999,999,999\ninclusive.",
                    "type": "integer"
                },
                "seconds": {
                    "description": "Represents seconds of UTC time since Unix epoch\n1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to\n9999-12-31T23:59:59Z inclusive.",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:2333",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "kk_etcd_go API",
	Description:      "kk_etcd_go terms.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
