basePath: /
definitions:
  kk_etcd_models.AllKVsBackupParam:
    type: object
  kk_etcd_models.AllKVsBackupResponse:
    properties:
      File:
        items:
          type: integer
        type: array
      Name:
        type: string
    type: object
  kk_etcd_models.AllKVsRestoreParam:
    properties:
      File:
        items:
          type: integer
        type: array
    type: object
  kk_etcd_models.AllKVsRestoreResponse:
    type: object
  kk_etcd_models.GetUserParam:
    properties:
      UserName:
        type: string
    type: object
  kk_etcd_models.GetUserResponse:
    properties:
      User:
        $ref: '#/definitions/kk_etcd_models.PBUser'
    type: object
  kk_etcd_models.KVDelParam:
    properties:
      Key:
        type: string
    type: object
  kk_etcd_models.KVDelResponse:
    type: object
  kk_etcd_models.KVGetParam:
    properties:
      Key:
        type: string
    type: object
  kk_etcd_models.KVGetResponse:
    properties:
      KV:
        $ref: '#/definitions/kk_etcd_models.PBKV'
    type: object
  kk_etcd_models.KVListParam:
    properties:
      Prefix:
        type: string
    type: object
  kk_etcd_models.KVListResponse:
    properties:
      KVList:
        $ref: '#/definitions/kk_etcd_models.PBListKV'
    type: object
  kk_etcd_models.KVPutParam:
    properties:
      Key:
        type: string
      Value:
        type: string
    type: object
  kk_etcd_models.KVPutResponse:
    type: object
  kk_etcd_models.LoginParam:
    properties:
      Password:
        type: string
      UserName:
        type: string
    type: object
  kk_etcd_models.LoginResponse:
    properties:
      Token:
        type: string
    type: object
  kk_etcd_models.LogoutParam:
    type: object
  kk_etcd_models.LogoutResponse:
    type: object
  kk_etcd_models.MyInfoParam:
    type: object
  kk_etcd_models.MyInfoResponse:
    properties:
      Roles:
        items:
          type: string
        type: array
      UserName:
        type: string
    type: object
  kk_etcd_models.PBKV:
    properties:
      Key:
        type: string
      Value:
        type: string
    type: object
  kk_etcd_models.PBListKV:
    properties:
      ListKV:
        items:
          $ref: '#/definitions/kk_etcd_models.PBKV'
        type: array
    type: object
  kk_etcd_models.PBListRole:
    properties:
      List:
        items:
          $ref: '#/definitions/kk_etcd_models.PBRole'
        type: array
    type: object
  kk_etcd_models.PBListServer:
    properties:
      ListServer:
        items:
          $ref: '#/definitions/kk_etcd_models.PBServer'
        type: array
    type: object
  kk_etcd_models.PBListUser:
    properties:
      ListUser:
        items:
          $ref: '#/definitions/kk_etcd_models.PBUser'
        type: array
    type: object
  kk_etcd_models.PBRole:
    properties:
      Key:
        type: string
      Name:
        type: string
      PermissionType:
        type: integer
      RangeEnd:
        type: string
    type: object
  kk_etcd_models.PBServer:
    properties:
      ServiceAddr:
        type: string
      ServiceName:
        type: string
    type: object
  kk_etcd_models.PBUser:
    properties:
      Password:
        type: string
      Roles:
        items:
          type: string
        type: array
      UserName:
        type: string
    type: object
  kk_etcd_models.RoleAddParam:
    properties:
      Name:
        type: string
    type: object
  kk_etcd_models.RoleAddResponse:
    type: object
  kk_etcd_models.RoleDeleteParam:
    properties:
      Name:
        type: string
    type: object
  kk_etcd_models.RoleDeleteResponse:
    type: object
  kk_etcd_models.RoleGetParam:
    properties:
      Name:
        type: string
    type: object
  kk_etcd_models.RoleGetResponse:
    properties:
      Role:
        $ref: '#/definitions/kk_etcd_models.PBRole'
    type: object
  kk_etcd_models.RoleGrantPermissionParam:
    properties:
      Role:
        $ref: '#/definitions/kk_etcd_models.PBRole'
    type: object
  kk_etcd_models.RoleGrantPermissionResponse:
    type: object
  kk_etcd_models.RoleListParam:
    type: object
  kk_etcd_models.RoleListResponse:
    properties:
      ListRole:
        $ref: '#/definitions/kk_etcd_models.PBListRole'
    type: object
  kk_etcd_models.ServerListParam:
    properties:
      Prefix:
        type: string
    type: object
  kk_etcd_models.ServerListResponse:
    properties:
      ServerList:
        $ref: '#/definitions/kk_etcd_models.PBListServer'
    type: object
  kk_etcd_models.SnapshotInfoParam:
    properties:
      File:
        items:
          type: integer
        type: array
    type: object
  kk_etcd_models.SnapshotInfoResponse:
    properties:
      Info:
        type: string
    type: object
  kk_etcd_models.SnapshotParam:
    type: object
  kk_etcd_models.SnapshotResponse:
    properties:
      File:
        items:
          type: integer
        type: array
      Name:
        type: string
    type: object
  kk_etcd_models.SnapshotRestoreParam:
    type: object
  kk_etcd_models.SnapshotRestoreResponse:
    properties:
      CmdStr:
        type: string
    type: object
  kk_etcd_models.UserAddParam:
    properties:
      Password:
        type: string
      Roles:
        items:
          type: string
        type: array
      UserName:
        type: string
    type: object
  kk_etcd_models.UserAddResponse:
    type: object
  kk_etcd_models.UserDeleteParam:
    properties:
      UserName:
        type: string
    type: object
  kk_etcd_models.UserDeleteResponse:
    type: object
  kk_etcd_models.UserGrantRoleParam:
    properties:
      Roles:
        items:
          type: string
        type: array
      UserName:
        type: string
    type: object
  kk_etcd_models.UserGrantRoleResponse:
    type: object
  kk_etcd_models.UserListParam:
    type: object
  kk_etcd_models.UserListResponse:
    properties:
      ListUser:
        $ref: '#/definitions/kk_etcd_models.PBListUser'
    type: object
host: localhost:2333
info:
  contact:
    email: kk_etcd_go@qq.com
    name: kk_etcd_go
    url: http://kk_etcd_go/support
  description: kk_etcd_go terms.
  license:
    name: Secret
    url: http://kk_etcd_go/licenses/LICENSE-2.0.html
  termsOfService: http://kk_etcd_go/terms/
  title: kk_etcd_go API
  version: "1.0"
paths:
  /backup/allKVsBackup:
    post:
      consumes:
      - application/octet-stream
      description: allKVsBackup
      parameters:
      - description: AllKVsBackupParam
        in: body
        name: AllKVsBackupParam
        required: true
        schema:
          $ref: '#/definitions/kk_etcd_models.AllKVsBackupParam'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kk_etcd_models.AllKVsBackupResponse'
  /backup/allKVsRestore:
    post:
      consumes:
      - application/octet-stream
      description: allKVsRestore
      parameters:
      - description: AllKVsRestoreParam
        in: body
        name: AllKVsRestoreParam
        required: true
        schema:
          $ref: '#/definitions/kk_etcd_models.AllKVsRestoreParam'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kk_etcd_models.AllKVsRestoreResponse'
  /backup/snapshot:
    post:
      consumes:
      - application/octet-stream
      description: snapshot
      parameters:
      - description: SnapshotParam
        in: body
        name: SnapshotParam
        required: true
        schema:
          $ref: '#/definitions/kk_etcd_models.SnapshotParam'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kk_etcd_models.SnapshotResponse'
  /backup/snapshotInfo:
    post:
      consumes:
      - application/octet-stream
      description: snapshotInfo
      parameters:
      - description: SnapshotInfoParam
        in: body
        name: SnapshotInfoParam
        required: true
        schema:
          $ref: '#/definitions/kk_etcd_models.SnapshotInfoParam'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kk_etcd_models.SnapshotInfoResponse'
  /backup/snapshotRestore:
    post:
      consumes:
      - application/octet-stream
      description: snapshotRestore
      parameters:
      - description: SnapshotRestoreParam
        in: body
        name: SnapshotRestoreParam
        required: true
        schema:
          $ref: '#/definitions/kk_etcd_models.SnapshotRestoreParam'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kk_etcd_models.SnapshotRestoreResponse'
  /kv/kVDel:
    post:
      consumes:
      - application/octet-stream
      description: kVDel
      parameters:
      - description: KVDelParam
        in: body
        name: KVDelParam
        required: true
        schema:
          $ref: '#/definitions/kk_etcd_models.KVDelParam'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kk_etcd_models.KVDelResponse'
  /kv/kVGet:
    post:
      consumes:
      - application/octet-stream
      description: kVGet
      parameters:
      - description: KVGetParam
        in: body
        name: KVGetParam
        required: true
        schema:
          $ref: '#/definitions/kk_etcd_models.KVGetParam'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kk_etcd_models.KVGetResponse'
  /kv/kVList:
    post:
      consumes:
      - application/octet-stream
      description: kVList
      parameters:
      - description: KVListParam
        in: body
        name: KVListParam
        required: true
        schema:
          $ref: '#/definitions/kk_etcd_models.KVListParam'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kk_etcd_models.KVListResponse'
  /kv/kVPut:
    post:
      consumes:
      - application/octet-stream
      description: kVPut
      parameters:
      - description: KVPutParam
        in: body
        name: KVPutParam
        required: true
        schema:
          $ref: '#/definitions/kk_etcd_models.KVPutParam'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kk_etcd_models.KVPutResponse'
  /role/roleAdd:
    post:
      consumes:
      - application/octet-stream
      description: roleAdd
      parameters:
      - description: RoleAddParam
        in: body
        name: RoleAddParam
        required: true
        schema:
          $ref: '#/definitions/kk_etcd_models.RoleAddParam'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kk_etcd_models.RoleAddResponse'
  /role/roleDelete:
    post:
      consumes:
      - application/octet-stream
      description: roleDelete
      parameters:
      - description: RoleDeleteParam
        in: body
        name: RoleDeleteParam
        required: true
        schema:
          $ref: '#/definitions/kk_etcd_models.RoleDeleteParam'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kk_etcd_models.RoleDeleteResponse'
  /role/roleGet:
    post:
      consumes:
      - application/octet-stream
      description: roleGet
      parameters:
      - description: RoleGetParam
        in: body
        name: RoleGetParam
        required: true
        schema:
          $ref: '#/definitions/kk_etcd_models.RoleGetParam'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kk_etcd_models.RoleGetResponse'
  /role/roleGrantPermission:
    post:
      consumes:
      - application/octet-stream
      description: roleGrantPermission
      parameters:
      - description: RoleGrantPermissionParam
        in: body
        name: RoleGrantPermissionParam
        required: true
        schema:
          $ref: '#/definitions/kk_etcd_models.RoleGrantPermissionParam'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kk_etcd_models.RoleGrantPermissionResponse'
  /role/roleList:
    post:
      consumes:
      - application/octet-stream
      description: roleList
      parameters:
      - description: RoleListParam
        in: body
        name: RoleListParam
        required: true
        schema:
          $ref: '#/definitions/kk_etcd_models.RoleListParam'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kk_etcd_models.RoleListResponse'
  /server/serverList:
    post:
      consumes:
      - application/octet-stream
      description: serverList
      parameters:
      - description: ServerListParam
        in: body
        name: ServerListParam
        required: true
        schema:
          $ref: '#/definitions/kk_etcd_models.ServerListParam'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kk_etcd_models.ServerListResponse'
  /user/getUser:
    post:
      consumes:
      - application/octet-stream
      description: getUser
      parameters:
      - description: GetUserParam
        in: body
        name: GetUserParam
        required: true
        schema:
          $ref: '#/definitions/kk_etcd_models.GetUserParam'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kk_etcd_models.GetUserResponse'
  /user/login:
    post:
      consumes:
      - application/octet-stream
      description: login
      parameters:
      - description: LoginParam
        in: body
        name: LoginParam
        required: true
        schema:
          $ref: '#/definitions/kk_etcd_models.LoginParam'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kk_etcd_models.LoginResponse'
  /user/logout:
    post:
      consumes:
      - application/octet-stream
      description: logout
      parameters:
      - description: LogoutParam
        in: body
        name: LogoutParam
        required: true
        schema:
          $ref: '#/definitions/kk_etcd_models.LogoutParam'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kk_etcd_models.LogoutResponse'
  /user/myInfo:
    post:
      consumes:
      - application/octet-stream
      description: myInfo
      parameters:
      - description: MyInfoParam
        in: body
        name: MyInfoParam
        required: true
        schema:
          $ref: '#/definitions/kk_etcd_models.MyInfoParam'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kk_etcd_models.MyInfoResponse'
  /user/userAdd:
    post:
      consumes:
      - application/octet-stream
      description: userAdd
      parameters:
      - description: UserAddParam
        in: body
        name: UserAddParam
        required: true
        schema:
          $ref: '#/definitions/kk_etcd_models.UserAddParam'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kk_etcd_models.UserAddResponse'
  /user/userDelete:
    post:
      consumes:
      - application/octet-stream
      description: userDelete
      parameters:
      - description: UserDeleteParam
        in: body
        name: UserDeleteParam
        required: true
        schema:
          $ref: '#/definitions/kk_etcd_models.UserDeleteParam'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kk_etcd_models.UserDeleteResponse'
  /user/userGrantRole:
    post:
      consumes:
      - application/octet-stream
      description: userGrantRole
      parameters:
      - description: UserGrantRoleParam
        in: body
        name: UserGrantRoleParam
        required: true
        schema:
          $ref: '#/definitions/kk_etcd_models.UserGrantRoleParam'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kk_etcd_models.UserGrantRoleResponse'
  /user/userList:
    post:
      consumes:
      - application/octet-stream
      description: userList
      parameters:
      - description: UserListParam
        in: body
        name: UserListParam
        required: true
        schema:
          $ref: '#/definitions/kk_etcd_models.UserListParam'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kk_etcd_models.UserListResponse'
swagger: "2.0"
