// Code generated by kk_api_gen. DO NOT EDIT.

package getUser

import (
	"gitee.com/cruvie/kk_go_kit/kk_http"
	"gitee.com/cruvie/kk_go_kit/kk_http/kk_global_stage"
	"gitee.com/cruvie/kk_go_kit/kk_stage"
	"github.com/gin-gonic/gin"
)

type api struct {
	stage *kk_stage.Stage
	in    *GetUser_Input
}

func newApi(c *gin.Context) *api {
	return &api{
		stage: kk_global_stage.GetRequestStage(c),
		in:    new(GetUser_Input),
	}
}

//  Handler
//	@Tags			user
//	@ID				GetUser
//	@Description	get user
//	@Accept			json,application/x-protobuf
//	@Produce		json,application/x-protobuf
//	@Param			GetUser_Input	body		GetUser_Input	true	"GetUser_Input"
//	@Success		200				{object}	GetUser_Output
//	@Router			/user/getUser [post]
func Handler(c *gin.Context) {
		x := newApi(c)
		span := x.stage.StartTrace("getUser")
		defer span.End()
	
		if err := x.bindCheck(x.stage); err != nil {
			kk_http.WriteResponse(x.stage, err, nil)
			return
		}
		err, resp := x.handler()
		kk_http.WriteResponse(x.stage, err, resp)
}