// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: api_role_kk_etcd.proto

package kk_etcd_models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleAddParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *RoleAddParam) Reset() {
	*x = RoleAddParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_role_kk_etcd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleAddParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAddParam) ProtoMessage() {}

func (x *RoleAddParam) ProtoReflect() protoreflect.Message {
	mi := &file_api_role_kk_etcd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAddParam.ProtoReflect.Descriptor instead.
func (*RoleAddParam) Descriptor() ([]byte, []int) {
	return file_api_role_kk_etcd_proto_rawDescGZIP(), []int{0}
}

func (x *RoleAddParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RoleAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleAddResponse) Reset() {
	*x = RoleAddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_role_kk_etcd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAddResponse) ProtoMessage() {}

func (x *RoleAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_role_kk_etcd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAddResponse.ProtoReflect.Descriptor instead.
func (*RoleAddResponse) Descriptor() ([]byte, []int) {
	return file_api_role_kk_etcd_proto_rawDescGZIP(), []int{1}
}

type RoleDeleteParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *RoleDeleteParam) Reset() {
	*x = RoleDeleteParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_role_kk_etcd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleDeleteParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDeleteParam) ProtoMessage() {}

func (x *RoleDeleteParam) ProtoReflect() protoreflect.Message {
	mi := &file_api_role_kk_etcd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDeleteParam.ProtoReflect.Descriptor instead.
func (*RoleDeleteParam) Descriptor() ([]byte, []int) {
	return file_api_role_kk_etcd_proto_rawDescGZIP(), []int{2}
}

func (x *RoleDeleteParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RoleDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleDeleteResponse) Reset() {
	*x = RoleDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_role_kk_etcd_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDeleteResponse) ProtoMessage() {}

func (x *RoleDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_role_kk_etcd_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDeleteResponse.ProtoReflect.Descriptor instead.
func (*RoleDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_role_kk_etcd_proto_rawDescGZIP(), []int{3}
}

type RoleGetParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *RoleGetParam) Reset() {
	*x = RoleGetParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_role_kk_etcd_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleGetParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGetParam) ProtoMessage() {}

func (x *RoleGetParam) ProtoReflect() protoreflect.Message {
	mi := &file_api_role_kk_etcd_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGetParam.ProtoReflect.Descriptor instead.
func (*RoleGetParam) Descriptor() ([]byte, []int) {
	return file_api_role_kk_etcd_proto_rawDescGZIP(), []int{4}
}

func (x *RoleGetParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RoleGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role *PBRole `protobuf:"bytes,1,opt,name=Role,proto3" json:"Role,omitempty"`
}

func (x *RoleGetResponse) Reset() {
	*x = RoleGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_role_kk_etcd_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGetResponse) ProtoMessage() {}

func (x *RoleGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_role_kk_etcd_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGetResponse.ProtoReflect.Descriptor instead.
func (*RoleGetResponse) Descriptor() ([]byte, []int) {
	return file_api_role_kk_etcd_proto_rawDescGZIP(), []int{5}
}

func (x *RoleGetResponse) GetRole() *PBRole {
	if x != nil {
		return x.Role
	}
	return nil
}

type RoleListParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleListParam) Reset() {
	*x = RoleListParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_role_kk_etcd_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleListParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListParam) ProtoMessage() {}

func (x *RoleListParam) ProtoReflect() protoreflect.Message {
	mi := &file_api_role_kk_etcd_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListParam.ProtoReflect.Descriptor instead.
func (*RoleListParam) Descriptor() ([]byte, []int) {
	return file_api_role_kk_etcd_proto_rawDescGZIP(), []int{6}
}

type RoleListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListRole *PBListRole `protobuf:"bytes,1,opt,name=ListRole,proto3" json:"ListRole,omitempty"`
}

func (x *RoleListResponse) Reset() {
	*x = RoleListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_role_kk_etcd_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListResponse) ProtoMessage() {}

func (x *RoleListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_role_kk_etcd_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListResponse.ProtoReflect.Descriptor instead.
func (*RoleListResponse) Descriptor() ([]byte, []int) {
	return file_api_role_kk_etcd_proto_rawDescGZIP(), []int{7}
}

func (x *RoleListResponse) GetListRole() *PBListRole {
	if x != nil {
		return x.ListRole
	}
	return nil
}

type RoleGrantPermissionParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string      `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Perm *Permission `protobuf:"bytes,2,opt,name=Perm,proto3" json:"Perm,omitempty"`
}

func (x *RoleGrantPermissionParam) Reset() {
	*x = RoleGrantPermissionParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_role_kk_etcd_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleGrantPermissionParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGrantPermissionParam) ProtoMessage() {}

func (x *RoleGrantPermissionParam) ProtoReflect() protoreflect.Message {
	mi := &file_api_role_kk_etcd_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGrantPermissionParam.ProtoReflect.Descriptor instead.
func (*RoleGrantPermissionParam) Descriptor() ([]byte, []int) {
	return file_api_role_kk_etcd_proto_rawDescGZIP(), []int{8}
}

func (x *RoleGrantPermissionParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleGrantPermissionParam) GetPerm() *Permission {
	if x != nil {
		return x.Perm
	}
	return nil
}

type RoleGrantPermissionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleGrantPermissionResponse) Reset() {
	*x = RoleGrantPermissionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_role_kk_etcd_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleGrantPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGrantPermissionResponse) ProtoMessage() {}

func (x *RoleGrantPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_role_kk_etcd_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGrantPermissionResponse.ProtoReflect.Descriptor instead.
func (*RoleGrantPermissionResponse) Descriptor() ([]byte, []int) {
	return file_api_role_kk_etcd_proto_rawDescGZIP(), []int{9}
}

var File_api_role_kk_etcd_proto protoreflect.FileDescriptor

var file_api_role_kk_etcd_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6b, 0x6b, 0x5f, 0x65, 0x74,
	0x63, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6b, 0x6b, 0x5f, 0x65, 0x74, 0x63,
	0x64, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x1a, 0x15, 0x70, 0x62, 0x5f, 0x72, 0x6f, 0x6c,
	0x65, 0x5f, 0x6b, 0x6b, 0x5f, 0x65, 0x74, 0x63, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x22, 0x0a, 0x0c, 0x52, 0x6f, 0x6c, 0x65, 0x41, 0x64, 0x64, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x52, 0x6f, 0x6c, 0x65, 0x41, 0x64, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25, 0x0a, 0x0f, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x14, 0x0a,
	0x12, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x22, 0x0a, 0x0c, 0x52, 0x6f, 0x6c, 0x65, 0x47, 0x65, 0x74, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3d, 0x0a, 0x0f, 0x52, 0x6f, 0x6c, 0x65, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x52, 0x6f,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6b, 0x6b, 0x5f, 0x65, 0x74,
	0x63, 0x64, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x50, 0x42, 0x52, 0x6f, 0x6c, 0x65,
	0x52, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x22, 0x4a, 0x0a, 0x10, 0x52, 0x6f, 0x6c, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x6b, 0x6b, 0x5f, 0x65, 0x74, 0x63, 0x64, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x50,
	0x42, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x6f, 0x6c, 0x65, 0x22, 0x5e, 0x0a, 0x18, 0x52, 0x6f, 0x6c, 0x65, 0x47, 0x72, 0x61, 0x6e, 0x74,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x50, 0x65, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x6b, 0x6b, 0x5f, 0x65, 0x74, 0x63, 0x64, 0x5f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x50,
	0x65, 0x72, 0x6d, 0x22, 0x1d, 0x0a, 0x1b, 0x52, 0x6f, 0x6c, 0x65, 0x47, 0x72, 0x61, 0x6e, 0x74,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x3b, 0x6b, 0x6b, 0x5f, 0x65, 0x74, 0x63, 0x64,
	0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_role_kk_etcd_proto_rawDescOnce sync.Once
	file_api_role_kk_etcd_proto_rawDescData = file_api_role_kk_etcd_proto_rawDesc
)

func file_api_role_kk_etcd_proto_rawDescGZIP() []byte {
	file_api_role_kk_etcd_proto_rawDescOnce.Do(func() {
		file_api_role_kk_etcd_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_role_kk_etcd_proto_rawDescData)
	})
	return file_api_role_kk_etcd_proto_rawDescData
}

var file_api_role_kk_etcd_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_role_kk_etcd_proto_goTypes = []any{
	(*RoleAddParam)(nil),                // 0: kk_etcd_models.RoleAddParam
	(*RoleAddResponse)(nil),             // 1: kk_etcd_models.RoleAddResponse
	(*RoleDeleteParam)(nil),             // 2: kk_etcd_models.RoleDeleteParam
	(*RoleDeleteResponse)(nil),          // 3: kk_etcd_models.RoleDeleteResponse
	(*RoleGetParam)(nil),                // 4: kk_etcd_models.RoleGetParam
	(*RoleGetResponse)(nil),             // 5: kk_etcd_models.RoleGetResponse
	(*RoleListParam)(nil),               // 6: kk_etcd_models.RoleListParam
	(*RoleListResponse)(nil),            // 7: kk_etcd_models.RoleListResponse
	(*RoleGrantPermissionParam)(nil),    // 8: kk_etcd_models.RoleGrantPermissionParam
	(*RoleGrantPermissionResponse)(nil), // 9: kk_etcd_models.RoleGrantPermissionResponse
	(*PBRole)(nil),                      // 10: kk_etcd_models.PBRole
	(*PBListRole)(nil),                  // 11: kk_etcd_models.PBListRole
	(*Permission)(nil),                  // 12: kk_etcd_models.Permission
}
var file_api_role_kk_etcd_proto_depIdxs = []int32{
	10, // 0: kk_etcd_models.RoleGetResponse.Role:type_name -> kk_etcd_models.PBRole
	11, // 1: kk_etcd_models.RoleListResponse.ListRole:type_name -> kk_etcd_models.PBListRole
	12, // 2: kk_etcd_models.RoleGrantPermissionParam.Perm:type_name -> kk_etcd_models.Permission
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_role_kk_etcd_proto_init() }
func file_api_role_kk_etcd_proto_init() {
	if File_api_role_kk_etcd_proto != nil {
		return
	}
	file_pb_role_kk_etcd_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_role_kk_etcd_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RoleAddParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_role_kk_etcd_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RoleAddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_role_kk_etcd_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*RoleDeleteParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_role_kk_etcd_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*RoleDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_role_kk_etcd_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*RoleGetParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_role_kk_etcd_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*RoleGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_role_kk_etcd_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*RoleListParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_role_kk_etcd_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*RoleListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_role_kk_etcd_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*RoleGrantPermissionParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_role_kk_etcd_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*RoleGrantPermissionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_role_kk_etcd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_role_kk_etcd_proto_goTypes,
		DependencyIndexes: file_api_role_kk_etcd_proto_depIdxs,
		MessageInfos:      file_api_role_kk_etcd_proto_msgTypes,
	}.Build()
	File_api_role_kk_etcd_proto = out.File
	file_api_role_kk_etcd_proto_rawDesc = nil
	file_api_role_kk_etcd_proto_goTypes = nil
	file_api_role_kk_etcd_proto_depIdxs = nil
}
