// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: kk_etcd_models/pb_role_kk_etcd.proto

package kk_etcd_models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Perms         []*PBPermission        `protobuf:"bytes,2,rep,name=Perms,proto3" json:"Perms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBRole) Reset() {
	*x = PBRole{}
	mi := &file_kk_etcd_models_pb_role_kk_etcd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBRole) ProtoMessage() {}

func (x *PBRole) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_models_pb_role_kk_etcd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBRole.ProtoReflect.Descriptor instead.
func (*PBRole) Descriptor() ([]byte, []int) {
	return file_kk_etcd_models_pb_role_kk_etcd_proto_rawDescGZIP(), []int{0}
}

func (x *PBRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PBRole) GetPerms() []*PBPermission {
	if x != nil {
		return x.Perms
	}
	return nil
}

type PBPermission struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Key      string                 `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	RangeEnd string                 `protobuf:"bytes,3,opt,name=RangeEnd,proto3" json:"RangeEnd,omitempty"`
	// authpb.READ 0
	// authpb.WRITE 1
	// authpb.READWRITE 2
	PermissionType int32 `protobuf:"varint,4,opt,name=PermissionType,proto3" json:"PermissionType,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PBPermission) Reset() {
	*x = PBPermission{}
	mi := &file_kk_etcd_models_pb_role_kk_etcd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBPermission) ProtoMessage() {}

func (x *PBPermission) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_models_pb_role_kk_etcd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBPermission.ProtoReflect.Descriptor instead.
func (*PBPermission) Descriptor() ([]byte, []int) {
	return file_kk_etcd_models_pb_role_kk_etcd_proto_rawDescGZIP(), []int{1}
}

func (x *PBPermission) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PBPermission) GetRangeEnd() string {
	if x != nil {
		return x.RangeEnd
	}
	return ""
}

func (x *PBPermission) GetPermissionType() int32 {
	if x != nil {
		return x.PermissionType
	}
	return 0
}

type PBListRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*PBRole              `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBListRole) Reset() {
	*x = PBListRole{}
	mi := &file_kk_etcd_models_pb_role_kk_etcd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBListRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBListRole) ProtoMessage() {}

func (x *PBListRole) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_models_pb_role_kk_etcd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBListRole.ProtoReflect.Descriptor instead.
func (*PBListRole) Descriptor() ([]byte, []int) {
	return file_kk_etcd_models_pb_role_kk_etcd_proto_rawDescGZIP(), []int{2}
}

func (x *PBListRole) GetList() []*PBRole {
	if x != nil {
		return x.List
	}
	return nil
}

var File_kk_etcd_models_pb_role_kk_etcd_proto protoreflect.FileDescriptor

const file_kk_etcd_models_pb_role_kk_etcd_proto_rawDesc = "" +
	"\n" +
	"$kk_etcd_models/pb_role_kk_etcd.proto\x12\x0ekk_etcd_models\"P\n" +
	"\x06PBRole\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x122\n" +
	"\x05Perms\x18\x02 \x03(\v2\x1c.kk_etcd_models.PBPermissionR\x05Perms\"d\n" +
	"\fPBPermission\x12\x10\n" +
	"\x03Key\x18\x02 \x01(\tR\x03Key\x12\x1a\n" +
	"\bRangeEnd\x18\x03 \x01(\tR\bRangeEnd\x12&\n" +
	"\x0ePermissionType\x18\x04 \x01(\x05R\x0ePermissionType\"8\n" +
	"\n" +
	"PBListRole\x12*\n" +
	"\x04List\x18\x01 \x03(\v2\x16.kk_etcd_models.PBRoleR\x04ListB-Z+github.com/cruvie/kk_etcd_go/kk_etcd_modelsb\x06proto3"

var (
	file_kk_etcd_models_pb_role_kk_etcd_proto_rawDescOnce sync.Once
	file_kk_etcd_models_pb_role_kk_etcd_proto_rawDescData []byte
)

func file_kk_etcd_models_pb_role_kk_etcd_proto_rawDescGZIP() []byte {
	file_kk_etcd_models_pb_role_kk_etcd_proto_rawDescOnce.Do(func() {
		file_kk_etcd_models_pb_role_kk_etcd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kk_etcd_models_pb_role_kk_etcd_proto_rawDesc), len(file_kk_etcd_models_pb_role_kk_etcd_proto_rawDesc)))
	})
	return file_kk_etcd_models_pb_role_kk_etcd_proto_rawDescData
}

var file_kk_etcd_models_pb_role_kk_etcd_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kk_etcd_models_pb_role_kk_etcd_proto_goTypes = []any{
	(*PBRole)(nil),       // 0: kk_etcd_models.PBRole
	(*PBPermission)(nil), // 1: kk_etcd_models.PBPermission
	(*PBListRole)(nil),   // 2: kk_etcd_models.PBListRole
}
var file_kk_etcd_models_pb_role_kk_etcd_proto_depIdxs = []int32{
	1, // 0: kk_etcd_models.PBRole.Perms:type_name -> kk_etcd_models.PBPermission
	0, // 1: kk_etcd_models.PBListRole.List:type_name -> kk_etcd_models.PBRole
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kk_etcd_models_pb_role_kk_etcd_proto_init() }
func file_kk_etcd_models_pb_role_kk_etcd_proto_init() {
	if File_kk_etcd_models_pb_role_kk_etcd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_etcd_models_pb_role_kk_etcd_proto_rawDesc), len(file_kk_etcd_models_pb_role_kk_etcd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_etcd_models_pb_role_kk_etcd_proto_goTypes,
		DependencyIndexes: file_kk_etcd_models_pb_role_kk_etcd_proto_depIdxs,
		MessageInfos:      file_kk_etcd_models_pb_role_kk_etcd_proto_msgTypes,
	}.Build()
	File_kk_etcd_models_pb_role_kk_etcd_proto = out.File
	file_kk_etcd_models_pb_role_kk_etcd_proto_goTypes = nil
	file_kk_etcd_models_pb_role_kk_etcd_proto_depIdxs = nil
}
