// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: kk_etcd_models/pb_server_kk_etcd.proto

package kk_etcd_models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBServer_ServerStatus int32

const (
	PBServer_UnKnown PBServer_ServerStatus = 0
	PBServer_Running PBServer_ServerStatus = 1
	PBServer_Stop    PBServer_ServerStatus = 2
	PBServer_Init    PBServer_ServerStatus = 3
)

// Enum value maps for PBServer_ServerStatus.
var (
	PBServer_ServerStatus_name = map[int32]string{
		0: "UnKnown",
		1: "Running",
		2: "Stop",
		3: "Init",
	}
	PBServer_ServerStatus_value = map[string]int32{
		"UnKnown": 0,
		"Running": 1,
		"Stop":    2,
		"Init":    3,
	}
)

func (x PBServer_ServerStatus) Enum() *PBServer_ServerStatus {
	p := new(PBServer_ServerStatus)
	*p = x
	return p
}

func (x PBServer_ServerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PBServer_ServerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_kk_etcd_models_pb_server_kk_etcd_proto_enumTypes[0].Descriptor()
}

func (PBServer_ServerStatus) Type() protoreflect.EnumType {
	return &file_kk_etcd_models_pb_server_kk_etcd_proto_enumTypes[0]
}

func (x PBServer_ServerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PBServer_ServerStatus.Descriptor instead.
func (PBServer_ServerStatus) EnumDescriptor() ([]byte, []int) {
	return file_kk_etcd_models_pb_server_kk_etcd_proto_rawDescGZIP(), []int{0, 0}
}

type PBServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerType    string                 `protobuf:"bytes,2,opt,name=ServerType,proto3" json:"ServerType,omitempty"`
	EndpointKey   string                 `protobuf:"bytes,3,opt,name=EndpointKey,proto3" json:"EndpointKey,omitempty"`
	EndpointAddr  string                 `protobuf:"bytes,4,opt,name=EndpointAddr,proto3" json:"EndpointAddr,omitempty"`
	Status        PBServer_ServerStatus  `protobuf:"varint,5,opt,name=Status,proto3,enum=kk_etcd_models.PBServer_ServerStatus" json:"Status,omitempty"`
	LastCheck     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=LastCheck,proto3" json:"LastCheck,omitempty"`
	Msg           string                 `protobuf:"bytes,7,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBServer) Reset() {
	*x = PBServer{}
	mi := &file_kk_etcd_models_pb_server_kk_etcd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBServer) ProtoMessage() {}

func (x *PBServer) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_models_pb_server_kk_etcd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBServer.ProtoReflect.Descriptor instead.
func (*PBServer) Descriptor() ([]byte, []int) {
	return file_kk_etcd_models_pb_server_kk_etcd_proto_rawDescGZIP(), []int{0}
}

func (x *PBServer) GetServerType() string {
	if x != nil {
		return x.ServerType
	}
	return ""
}

func (x *PBServer) GetEndpointKey() string {
	if x != nil {
		return x.EndpointKey
	}
	return ""
}

func (x *PBServer) GetEndpointAddr() string {
	if x != nil {
		return x.EndpointAddr
	}
	return ""
}

func (x *PBServer) GetStatus() PBServer_ServerStatus {
	if x != nil {
		return x.Status
	}
	return PBServer_UnKnown
}

func (x *PBServer) GetLastCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheck
	}
	return nil
}

func (x *PBServer) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type PBListServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListServer    []*PBServer            `protobuf:"bytes,1,rep,name=ListServer,proto3" json:"ListServer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBListServer) Reset() {
	*x = PBListServer{}
	mi := &file_kk_etcd_models_pb_server_kk_etcd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBListServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBListServer) ProtoMessage() {}

func (x *PBListServer) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_models_pb_server_kk_etcd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBListServer.ProtoReflect.Descriptor instead.
func (*PBListServer) Descriptor() ([]byte, []int) {
	return file_kk_etcd_models_pb_server_kk_etcd_proto_rawDescGZIP(), []int{1}
}

func (x *PBListServer) GetListServer() []*PBServer {
	if x != nil {
		return x.ListServer
	}
	return nil
}

var File_kk_etcd_models_pb_server_kk_etcd_proto protoreflect.FileDescriptor

const file_kk_etcd_models_pb_server_kk_etcd_proto_rawDesc = "" +
	"\n" +
	"&kk_etcd_models/pb_server_kk_etcd.proto\x12\x0ekk_etcd_models\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x02\n" +
	"\bPBServer\x12\x1e\n" +
	"\n" +
	"ServerType\x18\x02 \x01(\tR\n" +
	"ServerType\x12 \n" +
	"\vEndpointKey\x18\x03 \x01(\tR\vEndpointKey\x12\"\n" +
	"\fEndpointAddr\x18\x04 \x01(\tR\fEndpointAddr\x12=\n" +
	"\x06Status\x18\x05 \x01(\x0e2%.kk_etcd_models.PBServer.ServerStatusR\x06Status\x128\n" +
	"\tLastCheck\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tLastCheck\x12\x10\n" +
	"\x03Msg\x18\a \x01(\tR\x03Msg\"<\n" +
	"\fServerStatus\x12\v\n" +
	"\aUnKnown\x10\x00\x12\v\n" +
	"\aRunning\x10\x01\x12\b\n" +
	"\x04Stop\x10\x02\x12\b\n" +
	"\x04Init\x10\x03\"H\n" +
	"\fPBListServer\x128\n" +
	"\n" +
	"ListServer\x18\x01 \x03(\v2\x18.kk_etcd_models.PBServerR\n" +
	"ListServerB-Z+github.com/cruvie/kk_etcd_go/kk_etcd_modelsb\x06proto3"

var (
	file_kk_etcd_models_pb_server_kk_etcd_proto_rawDescOnce sync.Once
	file_kk_etcd_models_pb_server_kk_etcd_proto_rawDescData []byte
)

func file_kk_etcd_models_pb_server_kk_etcd_proto_rawDescGZIP() []byte {
	file_kk_etcd_models_pb_server_kk_etcd_proto_rawDescOnce.Do(func() {
		file_kk_etcd_models_pb_server_kk_etcd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kk_etcd_models_pb_server_kk_etcd_proto_rawDesc), len(file_kk_etcd_models_pb_server_kk_etcd_proto_rawDesc)))
	})
	return file_kk_etcd_models_pb_server_kk_etcd_proto_rawDescData
}

var file_kk_etcd_models_pb_server_kk_etcd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kk_etcd_models_pb_server_kk_etcd_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kk_etcd_models_pb_server_kk_etcd_proto_goTypes = []any{
	(PBServer_ServerStatus)(0),    // 0: kk_etcd_models.PBServer.ServerStatus
	(*PBServer)(nil),              // 1: kk_etcd_models.PBServer
	(*PBListServer)(nil),          // 2: kk_etcd_models.PBListServer
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_kk_etcd_models_pb_server_kk_etcd_proto_depIdxs = []int32{
	0, // 0: kk_etcd_models.PBServer.Status:type_name -> kk_etcd_models.PBServer.ServerStatus
	3, // 1: kk_etcd_models.PBServer.LastCheck:type_name -> google.protobuf.Timestamp
	1, // 2: kk_etcd_models.PBListServer.ListServer:type_name -> kk_etcd_models.PBServer
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kk_etcd_models_pb_server_kk_etcd_proto_init() }
func file_kk_etcd_models_pb_server_kk_etcd_proto_init() {
	if File_kk_etcd_models_pb_server_kk_etcd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_etcd_models_pb_server_kk_etcd_proto_rawDesc), len(file_kk_etcd_models_pb_server_kk_etcd_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_etcd_models_pb_server_kk_etcd_proto_goTypes,
		DependencyIndexes: file_kk_etcd_models_pb_server_kk_etcd_proto_depIdxs,
		EnumInfos:         file_kk_etcd_models_pb_server_kk_etcd_proto_enumTypes,
		MessageInfos:      file_kk_etcd_models_pb_server_kk_etcd_proto_msgTypes,
	}.Build()
	File_kk_etcd_models_pb_server_kk_etcd_proto = out.File
	file_kk_etcd_models_pb_server_kk_etcd_proto_goTypes = nil
	file_kk_etcd_models_pb_server_kk_etcd_proto_depIdxs = nil
}
