// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: kk_etcd_models/pb_service_kk_etcd.proto

package kk_etcd_models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBService_ServiceStatus int32

const (
	PBService_UnKnown PBService_ServiceStatus = 0
	PBService_Running PBService_ServiceStatus = 1
	PBService_Stop    PBService_ServiceStatus = 2
)

// Enum value maps for PBService_ServiceStatus.
var (
	PBService_ServiceStatus_name = map[int32]string{
		0: "UnKnown",
		1: "Running",
		2: "Stop",
	}
	PBService_ServiceStatus_value = map[string]int32{
		"UnKnown": 0,
		"Running": 1,
		"Stop":    2,
	}
)

func (x PBService_ServiceStatus) Enum() *PBService_ServiceStatus {
	p := new(PBService_ServiceStatus)
	*p = x
	return p
}

func (x PBService_ServiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PBService_ServiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_kk_etcd_models_pb_service_kk_etcd_proto_enumTypes[0].Descriptor()
}

func (PBService_ServiceStatus) Type() protoreflect.EnumType {
	return &file_kk_etcd_models_pb_service_kk_etcd_proto_enumTypes[0]
}

func (x PBService_ServiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PBService_ServiceStatus.Descriptor instead.
func (PBService_ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_kk_etcd_models_pb_service_kk_etcd_proto_rawDescGZIP(), []int{0, 0}
}

type PBService struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	ServiceRegistration *PBServiceRegistration  `protobuf:"bytes,1,opt,name=ServiceRegistration,proto3" json:"ServiceRegistration,omitempty"`
	Status              PBService_ServiceStatus `protobuf:"varint,5,opt,name=Status,proto3,enum=kk_etcd_models.PBService_ServiceStatus" json:"Status,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PBService) Reset() {
	*x = PBService{}
	mi := &file_kk_etcd_models_pb_service_kk_etcd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBService) ProtoMessage() {}

func (x *PBService) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_models_pb_service_kk_etcd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBService.ProtoReflect.Descriptor instead.
func (*PBService) Descriptor() ([]byte, []int) {
	return file_kk_etcd_models_pb_service_kk_etcd_proto_rawDescGZIP(), []int{0}
}

func (x *PBService) GetServiceRegistration() *PBServiceRegistration {
	if x != nil {
		return x.ServiceRegistration
	}
	return nil
}

func (x *PBService) GetStatus() PBService_ServiceStatus {
	if x != nil {
		return x.Status
	}
	return PBService_UnKnown
}

type PBListService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListService   []*PBService           `protobuf:"bytes,1,rep,name=ListService,proto3" json:"ListService,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBListService) Reset() {
	*x = PBListService{}
	mi := &file_kk_etcd_models_pb_service_kk_etcd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBListService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBListService) ProtoMessage() {}

func (x *PBListService) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_models_pb_service_kk_etcd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBListService.ProtoReflect.Descriptor instead.
func (*PBListService) Descriptor() ([]byte, []int) {
	return file_kk_etcd_models_pb_service_kk_etcd_proto_rawDescGZIP(), []int{1}
}

func (x *PBListService) GetListService() []*PBService {
	if x != nil {
		return x.ListService
	}
	return nil
}

var File_kk_etcd_models_pb_service_kk_etcd_proto protoreflect.FileDescriptor

const file_kk_etcd_models_pb_service_kk_etcd_proto_rawDesc = "" +
	"\n" +
	"'kk_etcd_models/pb_service_kk_etcd.proto\x12\x0ekk_etcd_models\x1a,kk_etcd_models/pb_service_registration.proto\"\xda\x01\n" +
	"\tPBService\x12W\n" +
	"\x13ServiceRegistration\x18\x01 \x01(\v2%.kk_etcd_models.PBServiceRegistrationR\x13ServiceRegistration\x12?\n" +
	"\x06Status\x18\x05 \x01(\x0e2'.kk_etcd_models.PBService.ServiceStatusR\x06Status\"3\n" +
	"\rServiceStatus\x12\v\n" +
	"\aUnKnown\x10\x00\x12\v\n" +
	"\aRunning\x10\x01\x12\b\n" +
	"\x04Stop\x10\x02\"L\n" +
	"\rPBListService\x12;\n" +
	"\vListService\x18\x01 \x03(\v2\x19.kk_etcd_models.PBServiceR\vListServiceB-Z+github.com/cruvie/kk_etcd_go/kk_etcd_modelsb\x06proto3"

var (
	file_kk_etcd_models_pb_service_kk_etcd_proto_rawDescOnce sync.Once
	file_kk_etcd_models_pb_service_kk_etcd_proto_rawDescData []byte
)

func file_kk_etcd_models_pb_service_kk_etcd_proto_rawDescGZIP() []byte {
	file_kk_etcd_models_pb_service_kk_etcd_proto_rawDescOnce.Do(func() {
		file_kk_etcd_models_pb_service_kk_etcd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kk_etcd_models_pb_service_kk_etcd_proto_rawDesc), len(file_kk_etcd_models_pb_service_kk_etcd_proto_rawDesc)))
	})
	return file_kk_etcd_models_pb_service_kk_etcd_proto_rawDescData
}

var file_kk_etcd_models_pb_service_kk_etcd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kk_etcd_models_pb_service_kk_etcd_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kk_etcd_models_pb_service_kk_etcd_proto_goTypes = []any{
	(PBService_ServiceStatus)(0),  // 0: kk_etcd_models.PBService.ServiceStatus
	(*PBService)(nil),             // 1: kk_etcd_models.PBService
	(*PBListService)(nil),         // 2: kk_etcd_models.PBListService
	(*PBServiceRegistration)(nil), // 3: kk_etcd_models.PBServiceRegistration
}
var file_kk_etcd_models_pb_service_kk_etcd_proto_depIdxs = []int32{
	3, // 0: kk_etcd_models.PBService.ServiceRegistration:type_name -> kk_etcd_models.PBServiceRegistration
	0, // 1: kk_etcd_models.PBService.Status:type_name -> kk_etcd_models.PBService.ServiceStatus
	1, // 2: kk_etcd_models.PBListService.ListService:type_name -> kk_etcd_models.PBService
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kk_etcd_models_pb_service_kk_etcd_proto_init() }
func file_kk_etcd_models_pb_service_kk_etcd_proto_init() {
	if File_kk_etcd_models_pb_service_kk_etcd_proto != nil {
		return
	}
	file_kk_etcd_models_pb_service_registration_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_etcd_models_pb_service_kk_etcd_proto_rawDesc), len(file_kk_etcd_models_pb_service_kk_etcd_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_etcd_models_pb_service_kk_etcd_proto_goTypes,
		DependencyIndexes: file_kk_etcd_models_pb_service_kk_etcd_proto_depIdxs,
		EnumInfos:         file_kk_etcd_models_pb_service_kk_etcd_proto_enumTypes,
		MessageInfos:      file_kk_etcd_models_pb_service_kk_etcd_proto_msgTypes,
	}.Build()
	File_kk_etcd_models_pb_service_kk_etcd_proto = out.File
	file_kk_etcd_models_pb_service_kk_etcd_proto_goTypes = nil
	file_kk_etcd_models_pb_service_kk_etcd_proto_depIdxs = nil
}
