// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: kk_etcd_models/pb_service_registration.proto

package kk_etcd_models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBServiceType int32

const (
	PBServiceType_Unknown PBServiceType = 0
	PBServiceType_Http    PBServiceType = 1
	PBServiceType_Grpc    PBServiceType = 2
)

// Enum value maps for PBServiceType.
var (
	PBServiceType_name = map[int32]string{
		0: "Unknown",
		1: "Http",
		2: "Grpc",
	}
	PBServiceType_value = map[string]int32{
		"Unknown": 0,
		"Http":    1,
		"Grpc":    2,
	}
)

func (x PBServiceType) Enum() *PBServiceType {
	p := new(PBServiceType)
	*p = x
	return p
}

func (x PBServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PBServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_kk_etcd_models_pb_service_registration_proto_enumTypes[0].Descriptor()
}

func (PBServiceType) Type() protoreflect.EnumType {
	return &file_kk_etcd_models_pb_service_registration_proto_enumTypes[0]
}

func (x PBServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PBServiceType.Descriptor instead.
func (PBServiceType) EnumDescriptor() ([]byte, []int) {
	return file_kk_etcd_models_pb_service_registration_proto_rawDescGZIP(), []int{0}
}

type PBServiceRegistration struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	ServiceType   PBServiceType                        `protobuf:"varint,1,opt,name=ServiceType,proto3,enum=kk_etcd_models.PBServiceType" json:"ServiceType,omitempty"`
	ServiceName   string                               `protobuf:"bytes,2,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	ServiceAddr   string                               `protobuf:"bytes,3,opt,name=ServiceAddr,proto3" json:"ServiceAddr,omitempty"`
	CheckConfig   *PBServiceRegistration_PBCheckConfig `protobuf:"bytes,4,opt,name=CheckConfig,proto3" json:"CheckConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBServiceRegistration) Reset() {
	*x = PBServiceRegistration{}
	mi := &file_kk_etcd_models_pb_service_registration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBServiceRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBServiceRegistration) ProtoMessage() {}

func (x *PBServiceRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_models_pb_service_registration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBServiceRegistration.ProtoReflect.Descriptor instead.
func (*PBServiceRegistration) Descriptor() ([]byte, []int) {
	return file_kk_etcd_models_pb_service_registration_proto_rawDescGZIP(), []int{0}
}

func (x *PBServiceRegistration) GetServiceType() PBServiceType {
	if x != nil {
		return x.ServiceType
	}
	return PBServiceType_Unknown
}

func (x *PBServiceRegistration) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *PBServiceRegistration) GetServiceAddr() string {
	if x != nil {
		return x.ServiceAddr
	}
	return ""
}

func (x *PBServiceRegistration) GetCheckConfig() *PBServiceRegistration_PBCheckConfig {
	if x != nil {
		return x.CheckConfig
	}
	return nil
}

type PBListServiceRegistration struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	List          []*PBServiceRegistration `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBListServiceRegistration) Reset() {
	*x = PBListServiceRegistration{}
	mi := &file_kk_etcd_models_pb_service_registration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBListServiceRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBListServiceRegistration) ProtoMessage() {}

func (x *PBListServiceRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_models_pb_service_registration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBListServiceRegistration.ProtoReflect.Descriptor instead.
func (*PBListServiceRegistration) Descriptor() ([]byte, []int) {
	return file_kk_etcd_models_pb_service_registration_proto_rawDescGZIP(), []int{1}
}

func (x *PBListServiceRegistration) GetList() []*PBServiceRegistration {
	if x != nil {
		return x.List
	}
	return nil
}

type PBServiceRegistration_PBCheckConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  PBServiceType          `protobuf:"varint,1,opt,name=Type,proto3,enum=kk_etcd_models.PBServiceType" json:"Type,omitempty"` // Http or Grpc
	// check timeout
	// must grater than 1 second
	Timeout *durationpb.Duration `protobuf:"bytes,2,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
	// check interval, kk_etcd will per Interval to send check request
	// must grater than Timeout
	Interval *durationpb.Duration `protobuf:"bytes,3,opt,name=Interval,proto3" json:"Interval,omitempty"`
	// Http default http://+Addr+/KKHealthCheck
	// Grpc Addr in ServiceRegistration
	Addr          string `protobuf:"bytes,4,opt,name=Addr,proto3" json:"Addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBServiceRegistration_PBCheckConfig) Reset() {
	*x = PBServiceRegistration_PBCheckConfig{}
	mi := &file_kk_etcd_models_pb_service_registration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBServiceRegistration_PBCheckConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBServiceRegistration_PBCheckConfig) ProtoMessage() {}

func (x *PBServiceRegistration_PBCheckConfig) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_models_pb_service_registration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBServiceRegistration_PBCheckConfig.ProtoReflect.Descriptor instead.
func (*PBServiceRegistration_PBCheckConfig) Descriptor() ([]byte, []int) {
	return file_kk_etcd_models_pb_service_registration_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PBServiceRegistration_PBCheckConfig) GetType() PBServiceType {
	if x != nil {
		return x.Type
	}
	return PBServiceType_Unknown
}

func (x *PBServiceRegistration_PBCheckConfig) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *PBServiceRegistration_PBCheckConfig) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *PBServiceRegistration_PBCheckConfig) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

var File_kk_etcd_models_pb_service_registration_proto protoreflect.FileDescriptor

const file_kk_etcd_models_pb_service_registration_proto_rawDesc = "" +
	"\n" +
	",kk_etcd_models/pb_service_registration.proto\x12\x0ekk_etcd_models\x1a\x1egoogle/protobuf/duration.proto\"\xb8\x03\n" +
	"\x15PBServiceRegistration\x12?\n" +
	"\vServiceType\x18\x01 \x01(\x0e2\x1d.kk_etcd_models.PBServiceTypeR\vServiceType\x12 \n" +
	"\vServiceName\x18\x02 \x01(\tR\vServiceName\x12 \n" +
	"\vServiceAddr\x18\x03 \x01(\tR\vServiceAddr\x12U\n" +
	"\vCheckConfig\x18\x04 \x01(\v23.kk_etcd_models.PBServiceRegistration.PBCheckConfigR\vCheckConfig\x1a\xc2\x01\n" +
	"\rPBCheckConfig\x121\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x1d.kk_etcd_models.PBServiceTypeR\x04Type\x123\n" +
	"\aTimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\aTimeout\x125\n" +
	"\bInterval\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bInterval\x12\x12\n" +
	"\x04Addr\x18\x04 \x01(\tR\x04Addr\"V\n" +
	"\x19PBListServiceRegistration\x129\n" +
	"\x04List\x18\x01 \x03(\v2%.kk_etcd_models.PBServiceRegistrationR\x04List*0\n" +
	"\rPBServiceType\x12\v\n" +
	"\aUnknown\x10\x00\x12\b\n" +
	"\x04Http\x10\x01\x12\b\n" +
	"\x04Grpc\x10\x02B-Z+github.com/cruvie/kk_etcd_go/kk_etcd_modelsb\x06proto3"

var (
	file_kk_etcd_models_pb_service_registration_proto_rawDescOnce sync.Once
	file_kk_etcd_models_pb_service_registration_proto_rawDescData []byte
)

func file_kk_etcd_models_pb_service_registration_proto_rawDescGZIP() []byte {
	file_kk_etcd_models_pb_service_registration_proto_rawDescOnce.Do(func() {
		file_kk_etcd_models_pb_service_registration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kk_etcd_models_pb_service_registration_proto_rawDesc), len(file_kk_etcd_models_pb_service_registration_proto_rawDesc)))
	})
	return file_kk_etcd_models_pb_service_registration_proto_rawDescData
}

var file_kk_etcd_models_pb_service_registration_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kk_etcd_models_pb_service_registration_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kk_etcd_models_pb_service_registration_proto_goTypes = []any{
	(PBServiceType)(0),                          // 0: kk_etcd_models.PBServiceType
	(*PBServiceRegistration)(nil),               // 1: kk_etcd_models.PBServiceRegistration
	(*PBListServiceRegistration)(nil),           // 2: kk_etcd_models.PBListServiceRegistration
	(*PBServiceRegistration_PBCheckConfig)(nil), // 3: kk_etcd_models.PBServiceRegistration.PBCheckConfig
	(*durationpb.Duration)(nil),                 // 4: google.protobuf.Duration
}
var file_kk_etcd_models_pb_service_registration_proto_depIdxs = []int32{
	0, // 0: kk_etcd_models.PBServiceRegistration.ServiceType:type_name -> kk_etcd_models.PBServiceType
	3, // 1: kk_etcd_models.PBServiceRegistration.CheckConfig:type_name -> kk_etcd_models.PBServiceRegistration.PBCheckConfig
	1, // 2: kk_etcd_models.PBListServiceRegistration.List:type_name -> kk_etcd_models.PBServiceRegistration
	0, // 3: kk_etcd_models.PBServiceRegistration.PBCheckConfig.Type:type_name -> kk_etcd_models.PBServiceType
	4, // 4: kk_etcd_models.PBServiceRegistration.PBCheckConfig.Timeout:type_name -> google.protobuf.Duration
	4, // 5: kk_etcd_models.PBServiceRegistration.PBCheckConfig.Interval:type_name -> google.protobuf.Duration
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_kk_etcd_models_pb_service_registration_proto_init() }
func file_kk_etcd_models_pb_service_registration_proto_init() {
	if File_kk_etcd_models_pb_service_registration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_etcd_models_pb_service_registration_proto_rawDesc), len(file_kk_etcd_models_pb_service_registration_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_etcd_models_pb_service_registration_proto_goTypes,
		DependencyIndexes: file_kk_etcd_models_pb_service_registration_proto_depIdxs,
		EnumInfos:         file_kk_etcd_models_pb_service_registration_proto_enumTypes,
		MessageInfos:      file_kk_etcd_models_pb_service_registration_proto_msgTypes,
	}.Build()
	File_kk_etcd_models_pb_service_registration_proto = out.File
	file_kk_etcd_models_pb_service_registration_proto_goTypes = nil
	file_kk_etcd_models_pb_service_registration_proto_depIdxs = nil
}
