// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: kk_etcd_models/pb_user_kk_etcd.proto

package kk_etcd_models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=Roles,proto3" json:"Roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBUser) Reset() {
	*x = PBUser{}
	mi := &file_kk_etcd_models_pb_user_kk_etcd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBUser) ProtoMessage() {}

func (x *PBUser) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_models_pb_user_kk_etcd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBUser.ProtoReflect.Descriptor instead.
func (*PBUser) Descriptor() ([]byte, []int) {
	return file_kk_etcd_models_pb_user_kk_etcd_proto_rawDescGZIP(), []int{0}
}

func (x *PBUser) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *PBUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *PBUser) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type PBListUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListUser      []*PBUser              `protobuf:"bytes,1,rep,name=ListUser,proto3" json:"ListUser,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBListUser) Reset() {
	*x = PBListUser{}
	mi := &file_kk_etcd_models_pb_user_kk_etcd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBListUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBListUser) ProtoMessage() {}

func (x *PBListUser) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_models_pb_user_kk_etcd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBListUser.ProtoReflect.Descriptor instead.
func (*PBListUser) Descriptor() ([]byte, []int) {
	return file_kk_etcd_models_pb_user_kk_etcd_proto_rawDescGZIP(), []int{1}
}

func (x *PBListUser) GetListUser() []*PBUser {
	if x != nil {
		return x.ListUser
	}
	return nil
}

var File_kk_etcd_models_pb_user_kk_etcd_proto protoreflect.FileDescriptor

const file_kk_etcd_models_pb_user_kk_etcd_proto_rawDesc = "" +
	"\n" +
	"$kk_etcd_models/pb_user_kk_etcd.proto\x12\x0ekk_etcd_models\"V\n" +
	"\x06PBUser\x12\x1a\n" +
	"\bUserName\x18\x02 \x01(\tR\bUserName\x12\x1a\n" +
	"\bPassword\x18\x03 \x01(\tR\bPassword\x12\x14\n" +
	"\x05Roles\x18\x04 \x03(\tR\x05Roles\"@\n" +
	"\n" +
	"PBListUser\x122\n" +
	"\bListUser\x18\x01 \x03(\v2\x16.kk_etcd_models.PBUserR\bListUserB-Z+github.com/cruvie/kk_etcd_go/kk_etcd_modelsb\x06proto3"

var (
	file_kk_etcd_models_pb_user_kk_etcd_proto_rawDescOnce sync.Once
	file_kk_etcd_models_pb_user_kk_etcd_proto_rawDescData []byte
)

func file_kk_etcd_models_pb_user_kk_etcd_proto_rawDescGZIP() []byte {
	file_kk_etcd_models_pb_user_kk_etcd_proto_rawDescOnce.Do(func() {
		file_kk_etcd_models_pb_user_kk_etcd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kk_etcd_models_pb_user_kk_etcd_proto_rawDesc), len(file_kk_etcd_models_pb_user_kk_etcd_proto_rawDesc)))
	})
	return file_kk_etcd_models_pb_user_kk_etcd_proto_rawDescData
}

var file_kk_etcd_models_pb_user_kk_etcd_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kk_etcd_models_pb_user_kk_etcd_proto_goTypes = []any{
	(*PBUser)(nil),     // 0: kk_etcd_models.PBUser
	(*PBListUser)(nil), // 1: kk_etcd_models.PBListUser
}
var file_kk_etcd_models_pb_user_kk_etcd_proto_depIdxs = []int32{
	0, // 0: kk_etcd_models.PBListUser.ListUser:type_name -> kk_etcd_models.PBUser
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kk_etcd_models_pb_user_kk_etcd_proto_init() }
func file_kk_etcd_models_pb_user_kk_etcd_proto_init() {
	if File_kk_etcd_models_pb_user_kk_etcd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_etcd_models_pb_user_kk_etcd_proto_rawDesc), len(file_kk_etcd_models_pb_user_kk_etcd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_etcd_models_pb_user_kk_etcd_proto_goTypes,
		DependencyIndexes: file_kk_etcd_models_pb_user_kk_etcd_proto_depIdxs,
		MessageInfos:      file_kk_etcd_models_pb_user_kk_etcd_proto_msgTypes,
	}.Build()
	File_kk_etcd_models_pb_user_kk_etcd_proto = out.File
	file_kk_etcd_models_pb_user_kk_etcd_proto_goTypes = nil
	file_kk_etcd_models_pb_user_kk_etcd_proto_depIdxs = nil
}
