// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: kk_etcd_api_hub/user/api_def/GetUser.proto

package api_def

import (
	kk_etcd_models "github.com/cruvie/kk_etcd_go/kk_etcd_models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// get user
type GetUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUser) Reset() {
	*x = GetUser{}
	mi := &file_kk_etcd_api_hub_user_api_def_GetUser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUser) ProtoMessage() {}

func (x *GetUser) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_user_api_def_GetUser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUser.ProtoReflect.Descriptor instead.
func (*GetUser) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_user_api_def_GetUser_proto_rawDescGZIP(), []int{0}
}

type GetUser_Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUser_Input) Reset() {
	*x = GetUser_Input{}
	mi := &file_kk_etcd_api_hub_user_api_def_GetUser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUser_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUser_Input) ProtoMessage() {}

func (x *GetUser_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_user_api_def_GetUser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUser_Input.ProtoReflect.Descriptor instead.
func (*GetUser_Input) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_user_api_def_GetUser_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetUser_Input) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type GetUser_Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *kk_etcd_models.PBUser `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUser_Output) Reset() {
	*x = GetUser_Output{}
	mi := &file_kk_etcd_api_hub_user_api_def_GetUser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUser_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUser_Output) ProtoMessage() {}

func (x *GetUser_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_user_api_def_GetUser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUser_Output.ProtoReflect.Descriptor instead.
func (*GetUser_Output) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_user_api_def_GetUser_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GetUser_Output) GetUser() *kk_etcd_models.PBUser {
	if x != nil {
		return x.User
	}
	return nil
}

var File_kk_etcd_api_hub_user_api_def_GetUser_proto protoreflect.FileDescriptor

const file_kk_etcd_api_hub_user_api_def_GetUser_proto_rawDesc = "" +
	"\n" +
	"*kk_etcd_api_hub/user/api_def/GetUser.proto\x12\aapi_def\x1a$kk_etcd_models/pb_user_kk_etcd.proto\"d\n" +
	"\aGetUser\x1a#\n" +
	"\x05Input\x12\x1a\n" +
	"\bUserName\x18\x01 \x01(\tR\bUserName\x1a4\n" +
	"\x06Output\x12*\n" +
	"\x04User\x18\x01 \x01(\v2\x16.kk_etcd_models.PBUserR\x04UserB\n" +
	"Z\b/api_defb\x06proto3"

var (
	file_kk_etcd_api_hub_user_api_def_GetUser_proto_rawDescOnce sync.Once
	file_kk_etcd_api_hub_user_api_def_GetUser_proto_rawDescData []byte
)

func file_kk_etcd_api_hub_user_api_def_GetUser_proto_rawDescGZIP() []byte {
	file_kk_etcd_api_hub_user_api_def_GetUser_proto_rawDescOnce.Do(func() {
		file_kk_etcd_api_hub_user_api_def_GetUser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kk_etcd_api_hub_user_api_def_GetUser_proto_rawDesc), len(file_kk_etcd_api_hub_user_api_def_GetUser_proto_rawDesc)))
	})
	return file_kk_etcd_api_hub_user_api_def_GetUser_proto_rawDescData
}

var file_kk_etcd_api_hub_user_api_def_GetUser_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kk_etcd_api_hub_user_api_def_GetUser_proto_goTypes = []any{
	(*GetUser)(nil),               // 0: api_def.GetUser
	(*GetUser_Input)(nil),         // 1: api_def.GetUser.Input
	(*GetUser_Output)(nil),        // 2: api_def.GetUser.Output
	(*kk_etcd_models.PBUser)(nil), // 3: kk_etcd_models.PBUser
}
var file_kk_etcd_api_hub_user_api_def_GetUser_proto_depIdxs = []int32{
	3, // 0: api_def.GetUser.Output.User:type_name -> kk_etcd_models.PBUser
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kk_etcd_api_hub_user_api_def_GetUser_proto_init() }
func file_kk_etcd_api_hub_user_api_def_GetUser_proto_init() {
	if File_kk_etcd_api_hub_user_api_def_GetUser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_etcd_api_hub_user_api_def_GetUser_proto_rawDesc), len(file_kk_etcd_api_hub_user_api_def_GetUser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_etcd_api_hub_user_api_def_GetUser_proto_goTypes,
		DependencyIndexes: file_kk_etcd_api_hub_user_api_def_GetUser_proto_depIdxs,
		MessageInfos:      file_kk_etcd_api_hub_user_api_def_GetUser_proto_msgTypes,
	}.Build()
	File_kk_etcd_api_hub_user_api_def_GetUser_proto = out.File
	file_kk_etcd_api_hub_user_api_def_GetUser_proto_goTypes = nil
	file_kk_etcd_api_hub_user_api_def_GetUser_proto_depIdxs = nil
}
