// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: kk_etcd_api_hub/user/api_def/Logout.proto

package api_def

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// logout
type Logout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Logout) Reset() {
	*x = Logout{}
	mi := &file_kk_etcd_api_hub_user_api_def_Logout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logout) ProtoMessage() {}

func (x *Logout) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_user_api_def_Logout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logout.ProtoReflect.Descriptor instead.
func (*Logout) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_user_api_def_Logout_proto_rawDescGZIP(), []int{0}
}

type Logout_Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Logout_Input) Reset() {
	*x = Logout_Input{}
	mi := &file_kk_etcd_api_hub_user_api_def_Logout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logout_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logout_Input) ProtoMessage() {}

func (x *Logout_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_user_api_def_Logout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logout_Input.ProtoReflect.Descriptor instead.
func (*Logout_Input) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_user_api_def_Logout_proto_rawDescGZIP(), []int{0, 0}
}

type Logout_Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Logout_Output) Reset() {
	*x = Logout_Output{}
	mi := &file_kk_etcd_api_hub_user_api_def_Logout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logout_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logout_Output) ProtoMessage() {}

func (x *Logout_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_user_api_def_Logout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logout_Output.ProtoReflect.Descriptor instead.
func (*Logout_Output) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_user_api_def_Logout_proto_rawDescGZIP(), []int{0, 1}
}

var File_kk_etcd_api_hub_user_api_def_Logout_proto protoreflect.FileDescriptor

const file_kk_etcd_api_hub_user_api_def_Logout_proto_rawDesc = "" +
	"\n" +
	")kk_etcd_api_hub/user/api_def/Logout.proto\x12\aapi_def\"\x1b\n" +
	"\x06Logout\x1a\a\n" +
	"\x05Input\x1a\b\n" +
	"\x06OutputB\n" +
	"Z\b/api_defb\x06proto3"

var (
	file_kk_etcd_api_hub_user_api_def_Logout_proto_rawDescOnce sync.Once
	file_kk_etcd_api_hub_user_api_def_Logout_proto_rawDescData []byte
)

func file_kk_etcd_api_hub_user_api_def_Logout_proto_rawDescGZIP() []byte {
	file_kk_etcd_api_hub_user_api_def_Logout_proto_rawDescOnce.Do(func() {
		file_kk_etcd_api_hub_user_api_def_Logout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kk_etcd_api_hub_user_api_def_Logout_proto_rawDesc), len(file_kk_etcd_api_hub_user_api_def_Logout_proto_rawDesc)))
	})
	return file_kk_etcd_api_hub_user_api_def_Logout_proto_rawDescData
}

var file_kk_etcd_api_hub_user_api_def_Logout_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kk_etcd_api_hub_user_api_def_Logout_proto_goTypes = []any{
	(*Logout)(nil),        // 0: api_def.Logout
	(*Logout_Input)(nil),  // 1: api_def.Logout.Input
	(*Logout_Output)(nil), // 2: api_def.Logout.Output
}
var file_kk_etcd_api_hub_user_api_def_Logout_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kk_etcd_api_hub_user_api_def_Logout_proto_init() }
func file_kk_etcd_api_hub_user_api_def_Logout_proto_init() {
	if File_kk_etcd_api_hub_user_api_def_Logout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_etcd_api_hub_user_api_def_Logout_proto_rawDesc), len(file_kk_etcd_api_hub_user_api_def_Logout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_etcd_api_hub_user_api_def_Logout_proto_goTypes,
		DependencyIndexes: file_kk_etcd_api_hub_user_api_def_Logout_proto_depIdxs,
		MessageInfos:      file_kk_etcd_api_hub_user_api_def_Logout_proto_msgTypes,
	}.Build()
	File_kk_etcd_api_hub_user_api_def_Logout_proto = out.File
	file_kk_etcd_api_hub_user_api_def_Logout_proto_goTypes = nil
	file_kk_etcd_api_hub_user_api_def_Logout_proto_depIdxs = nil
}
