// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: kk_etcd_api_hub/user/api_def/UserList.proto

package api_def

import (
	kk_etcd_models "github.com/cruvie/kk_etcd_go/kk_etcd_models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// list user
type UserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserList) Reset() {
	*x = UserList{}
	mi := &file_kk_etcd_api_hub_user_api_def_UserList_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_user_api_def_UserList_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_user_api_def_UserList_proto_rawDescGZIP(), []int{0}
}

type UserList_Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserList_Input) Reset() {
	*x = UserList_Input{}
	mi := &file_kk_etcd_api_hub_user_api_def_UserList_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserList_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList_Input) ProtoMessage() {}

func (x *UserList_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_user_api_def_UserList_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList_Input.ProtoReflect.Descriptor instead.
func (*UserList_Input) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_user_api_def_UserList_proto_rawDescGZIP(), []int{0, 0}
}

type UserList_Output struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	ListUser      *kk_etcd_models.PBListUser `protobuf:"bytes,1,opt,name=ListUser,proto3" json:"ListUser,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserList_Output) Reset() {
	*x = UserList_Output{}
	mi := &file_kk_etcd_api_hub_user_api_def_UserList_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserList_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList_Output) ProtoMessage() {}

func (x *UserList_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_user_api_def_UserList_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList_Output.ProtoReflect.Descriptor instead.
func (*UserList_Output) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_user_api_def_UserList_proto_rawDescGZIP(), []int{0, 1}
}

func (x *UserList_Output) GetListUser() *kk_etcd_models.PBListUser {
	if x != nil {
		return x.ListUser
	}
	return nil
}

var File_kk_etcd_api_hub_user_api_def_UserList_proto protoreflect.FileDescriptor

const file_kk_etcd_api_hub_user_api_def_UserList_proto_rawDesc = "" +
	"\n" +
	"+kk_etcd_api_hub/user/api_def/UserList.proto\x12\aapi_def\x1a$kk_etcd_models/pb_user_kk_etcd.proto\"U\n" +
	"\bUserList\x1a\a\n" +
	"\x05Input\x1a@\n" +
	"\x06Output\x126\n" +
	"\bListUser\x18\x01 \x01(\v2\x1a.kk_etcd_models.PBListUserR\bListUserB\n" +
	"Z\b/api_defb\x06proto3"

var (
	file_kk_etcd_api_hub_user_api_def_UserList_proto_rawDescOnce sync.Once
	file_kk_etcd_api_hub_user_api_def_UserList_proto_rawDescData []byte
)

func file_kk_etcd_api_hub_user_api_def_UserList_proto_rawDescGZIP() []byte {
	file_kk_etcd_api_hub_user_api_def_UserList_proto_rawDescOnce.Do(func() {
		file_kk_etcd_api_hub_user_api_def_UserList_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kk_etcd_api_hub_user_api_def_UserList_proto_rawDesc), len(file_kk_etcd_api_hub_user_api_def_UserList_proto_rawDesc)))
	})
	return file_kk_etcd_api_hub_user_api_def_UserList_proto_rawDescData
}

var file_kk_etcd_api_hub_user_api_def_UserList_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kk_etcd_api_hub_user_api_def_UserList_proto_goTypes = []any{
	(*UserList)(nil),                  // 0: api_def.UserList
	(*UserList_Input)(nil),            // 1: api_def.UserList.Input
	(*UserList_Output)(nil),           // 2: api_def.UserList.Output
	(*kk_etcd_models.PBListUser)(nil), // 3: kk_etcd_models.PBListUser
}
var file_kk_etcd_api_hub_user_api_def_UserList_proto_depIdxs = []int32{
	3, // 0: api_def.UserList.Output.ListUser:type_name -> kk_etcd_models.PBListUser
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kk_etcd_api_hub_user_api_def_UserList_proto_init() }
func file_kk_etcd_api_hub_user_api_def_UserList_proto_init() {
	if File_kk_etcd_api_hub_user_api_def_UserList_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_etcd_api_hub_user_api_def_UserList_proto_rawDesc), len(file_kk_etcd_api_hub_user_api_def_UserList_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_etcd_api_hub_user_api_def_UserList_proto_goTypes,
		DependencyIndexes: file_kk_etcd_api_hub_user_api_def_UserList_proto_depIdxs,
		MessageInfos:      file_kk_etcd_api_hub_user_api_def_UserList_proto_msgTypes,
	}.Build()
	File_kk_etcd_api_hub_user_api_def_UserList_proto = out.File
	file_kk_etcd_api_hub_user_api_def_UserList_proto_goTypes = nil
	file_kk_etcd_api_hub_user_api_def_UserList_proto_depIdxs = nil
}
