// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: kk_etcd_api_hub/service/api_def/DeregisterService.proto

package api_def

import (
	kk_etcd_models "github.com/cruvie/kk_etcd_go/kk_etcd_models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// deregister server
type DeregisterService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterService) Reset() {
	*x = DeregisterService{}
	mi := &file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterService) ProtoMessage() {}

func (x *DeregisterService) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterService.ProtoReflect.Descriptor instead.
func (*DeregisterService) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_rawDescGZIP(), []int{0}
}

type DeregisterService_Input struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Service       *kk_etcd_models.PBService `protobuf:"bytes,1,opt,name=Service,proto3" json:"Service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterService_Input) Reset() {
	*x = DeregisterService_Input{}
	mi := &file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterService_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterService_Input) ProtoMessage() {}

func (x *DeregisterService_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterService_Input.ProtoReflect.Descriptor instead.
func (*DeregisterService_Input) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DeregisterService_Input) GetService() *kk_etcd_models.PBService {
	if x != nil {
		return x.Service
	}
	return nil
}

type DeregisterService_Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterService_Output) Reset() {
	*x = DeregisterService_Output{}
	mi := &file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterService_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterService_Output) ProtoMessage() {}

func (x *DeregisterService_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterService_Output.ProtoReflect.Descriptor instead.
func (*DeregisterService_Output) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_rawDescGZIP(), []int{0, 1}
}

var File_kk_etcd_api_hub_service_api_def_DeregisterService_proto protoreflect.FileDescriptor

const file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_rawDesc = "" +
	"\n" +
	"7kk_etcd_api_hub/service/api_def/DeregisterService.proto\x12\aapi_def\x1a'kk_etcd_models/pb_service_kk_etcd.proto\"[\n" +
	"\x11DeregisterService\x1a<\n" +
	"\x05Input\x123\n" +
	"\aService\x18\x01 \x01(\v2\x19.kk_etcd_models.PBServiceR\aService\x1a\b\n" +
	"\x06OutputB\n" +
	"Z\b/api_defb\x06proto3"

var (
	file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_rawDescOnce sync.Once
	file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_rawDescData []byte
)

func file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_rawDescGZIP() []byte {
	file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_rawDescOnce.Do(func() {
		file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_rawDesc), len(file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_rawDesc)))
	})
	return file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_rawDescData
}

var file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_goTypes = []any{
	(*DeregisterService)(nil),        // 0: api_def.DeregisterService
	(*DeregisterService_Input)(nil),  // 1: api_def.DeregisterService.Input
	(*DeregisterService_Output)(nil), // 2: api_def.DeregisterService.Output
	(*kk_etcd_models.PBService)(nil), // 3: kk_etcd_models.PBService
}
var file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_depIdxs = []int32{
	3, // 0: api_def.DeregisterService.Input.Service:type_name -> kk_etcd_models.PBService
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_init() }
func file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_init() {
	if File_kk_etcd_api_hub_service_api_def_DeregisterService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_rawDesc), len(file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_goTypes,
		DependencyIndexes: file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_depIdxs,
		MessageInfos:      file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_msgTypes,
	}.Build()
	File_kk_etcd_api_hub_service_api_def_DeregisterService_proto = out.File
	file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_goTypes = nil
	file_kk_etcd_api_hub_service_api_def_DeregisterService_proto_depIdxs = nil
}
