// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: kk_etcd_api_hub/role/api_def/RoleGrantPermission.proto

package api_def

import (
	kk_etcd_models "github.com/cruvie/kk_etcd_go/kk_etcd_models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// grant permission
type RoleGrantPermission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleGrantPermission) Reset() {
	*x = RoleGrantPermission{}
	mi := &file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleGrantPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGrantPermission) ProtoMessage() {}

func (x *RoleGrantPermission) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGrantPermission.ProtoReflect.Descriptor instead.
func (*RoleGrantPermission) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_rawDescGZIP(), []int{0}
}

type RoleGrantPermission_Input struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Name          string                       `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Perm          *kk_etcd_models.PBPermission `protobuf:"bytes,2,opt,name=Perm,proto3" json:"Perm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleGrantPermission_Input) Reset() {
	*x = RoleGrantPermission_Input{}
	mi := &file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleGrantPermission_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGrantPermission_Input) ProtoMessage() {}

func (x *RoleGrantPermission_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGrantPermission_Input.ProtoReflect.Descriptor instead.
func (*RoleGrantPermission_Input) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RoleGrantPermission_Input) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleGrantPermission_Input) GetPerm() *kk_etcd_models.PBPermission {
	if x != nil {
		return x.Perm
	}
	return nil
}

type RoleGrantPermission_Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleGrantPermission_Output) Reset() {
	*x = RoleGrantPermission_Output{}
	mi := &file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleGrantPermission_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGrantPermission_Output) ProtoMessage() {}

func (x *RoleGrantPermission_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGrantPermission_Output.ProtoReflect.Descriptor instead.
func (*RoleGrantPermission_Output) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_rawDescGZIP(), []int{0, 1}
}

var File_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto protoreflect.FileDescriptor

const file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_rawDesc = "" +
	"\n" +
	"6kk_etcd_api_hub/role/api_def/RoleGrantPermission.proto\x12\aapi_def\x1a$kk_etcd_models/pb_role_kk_etcd.proto\"n\n" +
	"\x13RoleGrantPermission\x1aM\n" +
	"\x05Input\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x120\n" +
	"\x04Perm\x18\x02 \x01(\v2\x1c.kk_etcd_models.PBPermissionR\x04Perm\x1a\b\n" +
	"\x06OutputB\n" +
	"Z\b/api_defb\x06proto3"

var (
	file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_rawDescOnce sync.Once
	file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_rawDescData []byte
)

func file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_rawDescGZIP() []byte {
	file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_rawDescOnce.Do(func() {
		file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_rawDesc), len(file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_rawDesc)))
	})
	return file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_rawDescData
}

var file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_goTypes = []any{
	(*RoleGrantPermission)(nil),         // 0: api_def.RoleGrantPermission
	(*RoleGrantPermission_Input)(nil),   // 1: api_def.RoleGrantPermission.Input
	(*RoleGrantPermission_Output)(nil),  // 2: api_def.RoleGrantPermission.Output
	(*kk_etcd_models.PBPermission)(nil), // 3: kk_etcd_models.PBPermission
}
var file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_depIdxs = []int32{
	3, // 0: api_def.RoleGrantPermission.Input.Perm:type_name -> kk_etcd_models.PBPermission
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_init() }
func file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_init() {
	if File_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_rawDesc), len(file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_goTypes,
		DependencyIndexes: file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_depIdxs,
		MessageInfos:      file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_msgTypes,
	}.Build()
	File_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto = out.File
	file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_goTypes = nil
	file_kk_etcd_api_hub_role_api_def_RoleGrantPermission_proto_depIdxs = nil
}
