// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.25.0
// source: pb_base_proto_type.proto

package base_proto_type

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// protoc -I=. --dart_out=./dart *.proto
type PBString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *PBString) Reset() {
	*x = PBString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_base_proto_type_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBString) ProtoMessage() {}

func (x *PBString) ProtoReflect() protoreflect.Message {
	mi := &file_pb_base_proto_type_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBString.ProtoReflect.Descriptor instead.
func (*PBString) Descriptor() ([]byte, []int) {
	return file_pb_base_proto_type_proto_rawDescGZIP(), []int{0}
}

func (x *PBString) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PBBool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value bool `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *PBBool) Reset() {
	*x = PBBool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_base_proto_type_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBBool) ProtoMessage() {}

func (x *PBBool) ProtoReflect() protoreflect.Message {
	mi := &file_pb_base_proto_type_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBBool.ProtoReflect.Descriptor instead.
func (*PBBool) Descriptor() ([]byte, []int) {
	return file_pb_base_proto_type_proto_rawDescGZIP(), []int{1}
}

func (x *PBBool) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type PBListString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListString []string `protobuf:"bytes,1,rep,name=ListString,proto3" json:"ListString,omitempty"`
}

func (x *PBListString) Reset() {
	*x = PBListString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_base_proto_type_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBListString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBListString) ProtoMessage() {}

func (x *PBListString) ProtoReflect() protoreflect.Message {
	mi := &file_pb_base_proto_type_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBListString.ProtoReflect.Descriptor instead.
func (*PBListString) Descriptor() ([]byte, []int) {
	return file_pb_base_proto_type_proto_rawDescGZIP(), []int{2}
}

func (x *PBListString) GetListString() []string {
	if x != nil {
		return x.ListString
	}
	return nil
}

type PBUint64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value uint64 `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *PBUint64) Reset() {
	*x = PBUint64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_base_proto_type_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBUint64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBUint64) ProtoMessage() {}

func (x *PBUint64) ProtoReflect() protoreflect.Message {
	mi := &file_pb_base_proto_type_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBUint64.ProtoReflect.Descriptor instead.
func (*PBUint64) Descriptor() ([]byte, []int) {
	return file_pb_base_proto_type_proto_rawDescGZIP(), []int{3}
}

func (x *PBUint64) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_pb_base_proto_type_proto protoreflect.FileDescriptor

var file_pb_base_proto_type_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x62, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x62, 0x61, 0x73, 0x65,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0x20, 0x0a, 0x08, 0x50,
	0x42, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1e, 0x0a,
	0x06, 0x50, 0x42, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2e, 0x0a,
	0x0c, 0x50, 0x42, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1e, 0x0a,
	0x0a, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x20, 0x0a,
	0x08, 0x50, 0x42, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42,
	0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x3b, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_base_proto_type_proto_rawDescOnce sync.Once
	file_pb_base_proto_type_proto_rawDescData = file_pb_base_proto_type_proto_rawDesc
)

func file_pb_base_proto_type_proto_rawDescGZIP() []byte {
	file_pb_base_proto_type_proto_rawDescOnce.Do(func() {
		file_pb_base_proto_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_base_proto_type_proto_rawDescData)
	})
	return file_pb_base_proto_type_proto_rawDescData
}

var file_pb_base_proto_type_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_base_proto_type_proto_goTypes = []interface{}{
	(*PBString)(nil),     // 0: base_proto_type.PBString
	(*PBBool)(nil),       // 1: base_proto_type.PBBool
	(*PBListString)(nil), // 2: base_proto_type.PBListString
	(*PBUint64)(nil),     // 3: base_proto_type.PBUint64
}
var file_pb_base_proto_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_base_proto_type_proto_init() }
func file_pb_base_proto_type_proto_init() {
	if File_pb_base_proto_type_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_base_proto_type_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_base_proto_type_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBBool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_base_proto_type_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBListString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_base_proto_type_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBUint64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_base_proto_type_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_base_proto_type_proto_goTypes,
		DependencyIndexes: file_pb_base_proto_type_proto_depIdxs,
		MessageInfos:      file_pb_base_proto_type_proto_msgTypes,
	}.Build()
	File_pb_base_proto_type_proto = out.File
	file_pb_base_proto_type_proto_rawDesc = nil
	file_pb_base_proto_type_proto_goTypes = nil
	file_pb_base_proto_type_proto_depIdxs = nil
}
