version: "3"

services:

#  kk-etcd-go:
#    image: alpine:latest
#    container_name: kk-etcd-go
#    ports:
#      - "2333:2333"
#    restart: unless-stopped
#    volumes:
#      - ./kk_etcd_go:/kk_etcd_go/kk_etcd_go
#      - ./config:/kk_etcd_go/config
#    command: ./kk_etcd_go/kk_etcd_go

  kk-etcd-go:
    image: cruvie/kk_etcd_go:1.3.1
    container_name: kk-etcd-go
    ports:
      - "2333:2333"
    restart: unless-stopped
    volumes:
      - ./config/config.yml:/kk_etcd_go/config/config.yml
    networks:
      - ss-net

networks:
  ss-net:
    external: true