version: "3"

services:

  kk-etcd-go:
    image: cruvie/kk_etcd_go:1.3.3-arm64
    container_name: kk-etcd-go
    ports:
      - "2333:2333"
    restart: unless-stopped
    volumes:
      - ./config/config.yml:/kk_etcd_go/internal/config/config.yml
    networks:
      - ss-net

networks:
  ss-net:
    external: true