// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: kk_etcd_api_hub/server/deregisterServer/api.proto

package deregisterServer

import (
	kk_etcd_models "github.com/cruvie/kk_etcd_go/kk_etcd_models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// deregister server
type DeregisterServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterServer) Reset() {
	*x = DeregisterServer{}
	mi := &file_kk_etcd_api_hub_server_deregisterServer_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterServer) ProtoMessage() {}

func (x *DeregisterServer) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_server_deregisterServer_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterServer.ProtoReflect.Descriptor instead.
func (*DeregisterServer) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_server_deregisterServer_api_proto_rawDescGZIP(), []int{0}
}

type DeregisterServer_Input struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Server        *kk_etcd_models.PBServer `protobuf:"bytes,1,opt,name=Server,proto3" json:"Server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterServer_Input) Reset() {
	*x = DeregisterServer_Input{}
	mi := &file_kk_etcd_api_hub_server_deregisterServer_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterServer_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterServer_Input) ProtoMessage() {}

func (x *DeregisterServer_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_server_deregisterServer_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterServer_Input.ProtoReflect.Descriptor instead.
func (*DeregisterServer_Input) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_server_deregisterServer_api_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DeregisterServer_Input) GetServer() *kk_etcd_models.PBServer {
	if x != nil {
		return x.Server
	}
	return nil
}

type DeregisterServer_Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterServer_Output) Reset() {
	*x = DeregisterServer_Output{}
	mi := &file_kk_etcd_api_hub_server_deregisterServer_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterServer_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterServer_Output) ProtoMessage() {}

func (x *DeregisterServer_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_server_deregisterServer_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterServer_Output.ProtoReflect.Descriptor instead.
func (*DeregisterServer_Output) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_server_deregisterServer_api_proto_rawDescGZIP(), []int{0, 1}
}

var File_kk_etcd_api_hub_server_deregisterServer_api_proto protoreflect.FileDescriptor

var file_kk_etcd_api_hub_server_deregisterServer_api_proto_rawDesc = string([]byte{
	0x0a, 0x31, 0x6b, 0x6b, 0x5f, 0x65, 0x74, 0x63, 0x64, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x68, 0x75,
	0x62, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x64, 0x65, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x10, 0x64, 0x65, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x26, 0x6b, 0x6b, 0x5f, 0x65, 0x74, 0x63, 0x64, 0x5f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x70, 0x62, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x6b, 0x6b, 0x5f, 0x65, 0x74, 0x63, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x57, 0x0a,
	0x10, 0x44, 0x65, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x1a, 0x39, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x30, 0x0a, 0x06, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6b, 0x6b, 0x5f,
	0x65, 0x74, 0x63, 0x64, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x50, 0x42, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x08, 0x0a, 0x06,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x42, 0x13, 0x5a, 0x11, 0x2f, 0x64, 0x65, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_kk_etcd_api_hub_server_deregisterServer_api_proto_rawDescOnce sync.Once
	file_kk_etcd_api_hub_server_deregisterServer_api_proto_rawDescData []byte
)

func file_kk_etcd_api_hub_server_deregisterServer_api_proto_rawDescGZIP() []byte {
	file_kk_etcd_api_hub_server_deregisterServer_api_proto_rawDescOnce.Do(func() {
		file_kk_etcd_api_hub_server_deregisterServer_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kk_etcd_api_hub_server_deregisterServer_api_proto_rawDesc), len(file_kk_etcd_api_hub_server_deregisterServer_api_proto_rawDesc)))
	})
	return file_kk_etcd_api_hub_server_deregisterServer_api_proto_rawDescData
}

var file_kk_etcd_api_hub_server_deregisterServer_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kk_etcd_api_hub_server_deregisterServer_api_proto_goTypes = []any{
	(*DeregisterServer)(nil),        // 0: deregisterServer.DeregisterServer
	(*DeregisterServer_Input)(nil),  // 1: deregisterServer.DeregisterServer.Input
	(*DeregisterServer_Output)(nil), // 2: deregisterServer.DeregisterServer.Output
	(*kk_etcd_models.PBServer)(nil), // 3: kk_etcd_models.PBServer
}
var file_kk_etcd_api_hub_server_deregisterServer_api_proto_depIdxs = []int32{
	3, // 0: deregisterServer.DeregisterServer.Input.Server:type_name -> kk_etcd_models.PBServer
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kk_etcd_api_hub_server_deregisterServer_api_proto_init() }
func file_kk_etcd_api_hub_server_deregisterServer_api_proto_init() {
	if File_kk_etcd_api_hub_server_deregisterServer_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_etcd_api_hub_server_deregisterServer_api_proto_rawDesc), len(file_kk_etcd_api_hub_server_deregisterServer_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_etcd_api_hub_server_deregisterServer_api_proto_goTypes,
		DependencyIndexes: file_kk_etcd_api_hub_server_deregisterServer_api_proto_depIdxs,
		MessageInfos:      file_kk_etcd_api_hub_server_deregisterServer_api_proto_msgTypes,
	}.Build()
	File_kk_etcd_api_hub_server_deregisterServer_api_proto = out.File
	file_kk_etcd_api_hub_server_deregisterServer_api_proto_goTypes = nil
	file_kk_etcd_api_hub_server_deregisterServer_api_proto_depIdxs = nil
}
