// Code generated by grpc_api_gen. DO NOT EDIT.

package api_impl

import (
	"context"
	"google.golang.org/grpc"

	"gitee.com/cruvie/kk_go_kit/kk_grpc"

	"github.com/cruvie/kk_etcd_go/kk_etcd_api_hub/user/api_def"
	"github.com/cruvie/kk_etcd_go/kk_etcd_api_hub/user/api_handlers/getUser"
	"github.com/cruvie/kk_etcd_go/kk_etcd_api_hub/user/api_handlers/login"
	"github.com/cruvie/kk_etcd_go/kk_etcd_api_hub/user/api_handlers/logout"
	"github.com/cruvie/kk_etcd_go/kk_etcd_api_hub/user/api_handlers/myInfo"
	"github.com/cruvie/kk_etcd_go/kk_etcd_api_hub/user/api_handlers/userAdd"
	"github.com/cruvie/kk_etcd_go/kk_etcd_api_hub/user/api_handlers/userDelete"
	"github.com/cruvie/kk_etcd_go/kk_etcd_api_hub/user/api_handlers/userGrantRole"
	"github.com/cruvie/kk_etcd_go/kk_etcd_api_hub/user/api_handlers/userList"
)

type server struct {
	api_def.UnimplementedUserServer
}

func RegisterServer(grpcServer *grpc.Server) {
	api_def.RegisterUserServer(grpcServer, &server{})
}

func (x *server) GetUser(ctx context.Context, input *api_def.GetUser_Input) (*api_def.GetUser_Output, error) {
	return kk_grpc.GrpcHandler(
		ctx,
		input,
		getUser.NewApi,
	)
}

func (x *server) Login(ctx context.Context, input *api_def.Login_Input) (*api_def.Login_Output, error) {
	return kk_grpc.GrpcHandler(
		ctx,
		input,
		login.NewApi,
	)
}

func (x *server) Logout(ctx context.Context, input *api_def.Logout_Input) (*api_def.Logout_Output, error) {
	return kk_grpc.GrpcHandler(
		ctx,
		input,
		logout.NewApi,
	)
}

func (x *server) MyInfo(ctx context.Context, input *api_def.MyInfo_Input) (*api_def.MyInfo_Output, error) {
	return kk_grpc.GrpcHandler(
		ctx,
		input,
		myInfo.NewApi,
	)
}

func (x *server) UserAdd(ctx context.Context, input *api_def.UserAdd_Input) (*api_def.UserAdd_Output, error) {
	return kk_grpc.GrpcHandler(
		ctx,
		input,
		userAdd.NewApi,
	)
}

func (x *server) UserDelete(ctx context.Context, input *api_def.UserDelete_Input) (*api_def.UserDelete_Output, error) {
	return kk_grpc.GrpcHandler(
		ctx,
		input,
		userDelete.NewApi,
	)
}

func (x *server) UserGrantRole(ctx context.Context, input *api_def.UserGrantRole_Input) (*api_def.UserGrantRole_Output, error) {
	return kk_grpc.GrpcHandler(
		ctx,
		input,
		userGrantRole.NewApi,
	)
}

func (x *server) UserList(ctx context.Context, input *api_def.UserList_Input) (*api_def.UserList_Output, error) {
	return kk_grpc.GrpcHandler(
		ctx,
		input,
		userList.NewApi,
	)
}
