// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: internal/service_hub/backup/api_def/AllKVsRestore.proto

package api_def

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// all kvs restore
type AllKVsRestore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllKVsRestore) Reset() {
	*x = AllKVsRestore{}
	mi := &file_internal_service_hub_backup_api_def_AllKVsRestore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllKVsRestore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllKVsRestore) ProtoMessage() {}

func (x *AllKVsRestore) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_hub_backup_api_def_AllKVsRestore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllKVsRestore.ProtoReflect.Descriptor instead.
func (*AllKVsRestore) Descriptor() ([]byte, []int) {
	return file_internal_service_hub_backup_api_def_AllKVsRestore_proto_rawDescGZIP(), []int{0}
}

type AllKVsRestore_Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          []byte                 `protobuf:"bytes,2,opt,name=File,proto3" json:"File,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllKVsRestore_Input) Reset() {
	*x = AllKVsRestore_Input{}
	mi := &file_internal_service_hub_backup_api_def_AllKVsRestore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllKVsRestore_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllKVsRestore_Input) ProtoMessage() {}

func (x *AllKVsRestore_Input) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_hub_backup_api_def_AllKVsRestore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllKVsRestore_Input.ProtoReflect.Descriptor instead.
func (*AllKVsRestore_Input) Descriptor() ([]byte, []int) {
	return file_internal_service_hub_backup_api_def_AllKVsRestore_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AllKVsRestore_Input) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

type AllKVsRestore_Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllKVsRestore_Output) Reset() {
	*x = AllKVsRestore_Output{}
	mi := &file_internal_service_hub_backup_api_def_AllKVsRestore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllKVsRestore_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllKVsRestore_Output) ProtoMessage() {}

func (x *AllKVsRestore_Output) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_hub_backup_api_def_AllKVsRestore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllKVsRestore_Output.ProtoReflect.Descriptor instead.
func (*AllKVsRestore_Output) Descriptor() ([]byte, []int) {
	return file_internal_service_hub_backup_api_def_AllKVsRestore_proto_rawDescGZIP(), []int{0, 1}
}

var File_internal_service_hub_backup_api_def_AllKVsRestore_proto protoreflect.FileDescriptor

const file_internal_service_hub_backup_api_def_AllKVsRestore_proto_rawDesc = "" +
	"\n" +
	"7internal/service_hub/backup/api_def/AllKVsRestore.proto\x12\akk_etcd\"6\n" +
	"\rAllKVsRestore\x1a\x1b\n" +
	"\x05Input\x12\x12\n" +
	"\x04File\x18\x02 \x01(\fR\x04File\x1a\b\n" +
	"\x06OutputB\n" +
	"Z\b/api_defb\x06proto3"

var (
	file_internal_service_hub_backup_api_def_AllKVsRestore_proto_rawDescOnce sync.Once
	file_internal_service_hub_backup_api_def_AllKVsRestore_proto_rawDescData []byte
)

func file_internal_service_hub_backup_api_def_AllKVsRestore_proto_rawDescGZIP() []byte {
	file_internal_service_hub_backup_api_def_AllKVsRestore_proto_rawDescOnce.Do(func() {
		file_internal_service_hub_backup_api_def_AllKVsRestore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_service_hub_backup_api_def_AllKVsRestore_proto_rawDesc), len(file_internal_service_hub_backup_api_def_AllKVsRestore_proto_rawDesc)))
	})
	return file_internal_service_hub_backup_api_def_AllKVsRestore_proto_rawDescData
}

var file_internal_service_hub_backup_api_def_AllKVsRestore_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_service_hub_backup_api_def_AllKVsRestore_proto_goTypes = []any{
	(*AllKVsRestore)(nil),        // 0: kk_etcd.AllKVsRestore
	(*AllKVsRestore_Input)(nil),  // 1: kk_etcd.AllKVsRestore.Input
	(*AllKVsRestore_Output)(nil), // 2: kk_etcd.AllKVsRestore.Output
}
var file_internal_service_hub_backup_api_def_AllKVsRestore_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_service_hub_backup_api_def_AllKVsRestore_proto_init() }
func file_internal_service_hub_backup_api_def_AllKVsRestore_proto_init() {
	if File_internal_service_hub_backup_api_def_AllKVsRestore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_service_hub_backup_api_def_AllKVsRestore_proto_rawDesc), len(file_internal_service_hub_backup_api_def_AllKVsRestore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_service_hub_backup_api_def_AllKVsRestore_proto_goTypes,
		DependencyIndexes: file_internal_service_hub_backup_api_def_AllKVsRestore_proto_depIdxs,
		MessageInfos:      file_internal_service_hub_backup_api_def_AllKVsRestore_proto_msgTypes,
	}.Build()
	File_internal_service_hub_backup_api_def_AllKVsRestore_proto = out.File
	file_internal_service_hub_backup_api_def_AllKVsRestore_proto_goTypes = nil
	file_internal_service_hub_backup_api_def_AllKVsRestore_proto_depIdxs = nil
}
