// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: internal/service_hub/backup/api_def/service.proto

package api_def

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_internal_service_hub_backup_api_def_service_proto protoreflect.FileDescriptor

const file_internal_service_hub_backup_api_def_service_proto_rawDesc = "" +
	"\n" +
	"1internal/service_hub/backup/api_def/service.proto\x12\aapi_def\x1a6internal/service_hub/backup/api_def/AllKVsBackup.proto\x1a7internal/service_hub/backup/api_def/AllKVsRestore.proto\x1a2internal/service_hub/backup/api_def/Snapshot.proto\x1a6internal/service_hub/backup/api_def/SnapshotInfo.proto\x1a9internal/service_hub/backup/api_def/SnapshotRestore.proto2\xff\x02\n" +
	"\x06Backup\x12I\n" +
	"\fAllKVsBackup\x12\x1b.api_def.AllKVsBackup.Input\x1a\x1c.api_def.AllKVsBackup.Output\x12L\n" +
	"\rAllKVsRestore\x12\x1c.api_def.AllKVsRestore.Input\x1a\x1d.api_def.AllKVsRestore.Output\x12=\n" +
	"\bSnapshot\x12\x17.api_def.Snapshot.Input\x1a\x18.api_def.Snapshot.Output\x12I\n" +
	"\fSnapshotInfo\x12\x1b.api_def.SnapshotInfo.Input\x1a\x1c.api_def.SnapshotInfo.Output\x12R\n" +
	"\x0fSnapshotRestore\x12\x1e.api_def.SnapshotRestore.Input\x1a\x1f.api_def.SnapshotRestore.OutputB\n" +
	"Z\b/api_defb\x06proto3"

var file_internal_service_hub_backup_api_def_service_proto_goTypes = []any{
	(*AllKVsBackup_Input)(nil),     // 0: api_def.AllKVsBackup.Input
	(*AllKVsRestore_Input)(nil),    // 1: api_def.AllKVsRestore.Input
	(*Snapshot_Input)(nil),         // 2: api_def.Snapshot.Input
	(*SnapshotInfo_Input)(nil),     // 3: api_def.SnapshotInfo.Input
	(*SnapshotRestore_Input)(nil),  // 4: api_def.SnapshotRestore.Input
	(*AllKVsBackup_Output)(nil),    // 5: api_def.AllKVsBackup.Output
	(*AllKVsRestore_Output)(nil),   // 6: api_def.AllKVsRestore.Output
	(*Snapshot_Output)(nil),        // 7: api_def.Snapshot.Output
	(*SnapshotInfo_Output)(nil),    // 8: api_def.SnapshotInfo.Output
	(*SnapshotRestore_Output)(nil), // 9: api_def.SnapshotRestore.Output
}
var file_internal_service_hub_backup_api_def_service_proto_depIdxs = []int32{
	0, // 0: api_def.Backup.AllKVsBackup:input_type -> api_def.AllKVsBackup.Input
	1, // 1: api_def.Backup.AllKVsRestore:input_type -> api_def.AllKVsRestore.Input
	2, // 2: api_def.Backup.Snapshot:input_type -> api_def.Snapshot.Input
	3, // 3: api_def.Backup.SnapshotInfo:input_type -> api_def.SnapshotInfo.Input
	4, // 4: api_def.Backup.SnapshotRestore:input_type -> api_def.SnapshotRestore.Input
	5, // 5: api_def.Backup.AllKVsBackup:output_type -> api_def.AllKVsBackup.Output
	6, // 6: api_def.Backup.AllKVsRestore:output_type -> api_def.AllKVsRestore.Output
	7, // 7: api_def.Backup.Snapshot:output_type -> api_def.Snapshot.Output
	8, // 8: api_def.Backup.SnapshotInfo:output_type -> api_def.SnapshotInfo.Output
	9, // 9: api_def.Backup.SnapshotRestore:output_type -> api_def.SnapshotRestore.Output
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_service_hub_backup_api_def_service_proto_init() }
func file_internal_service_hub_backup_api_def_service_proto_init() {
	if File_internal_service_hub_backup_api_def_service_proto != nil {
		return
	}
	file_internal_service_hub_backup_api_def_AllKVsBackup_proto_init()
	file_internal_service_hub_backup_api_def_AllKVsRestore_proto_init()
	file_internal_service_hub_backup_api_def_Snapshot_proto_init()
	file_internal_service_hub_backup_api_def_SnapshotInfo_proto_init()
	file_internal_service_hub_backup_api_def_SnapshotRestore_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_service_hub_backup_api_def_service_proto_rawDesc), len(file_internal_service_hub_backup_api_def_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_service_hub_backup_api_def_service_proto_goTypes,
		DependencyIndexes: file_internal_service_hub_backup_api_def_service_proto_depIdxs,
	}.Build()
	File_internal_service_hub_backup_api_def_service_proto = out.File
	file_internal_service_hub_backup_api_def_service_proto_goTypes = nil
	file_internal_service_hub_backup_api_def_service_proto_depIdxs = nil
}
