// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: internal/service_hub/backup/api_def/service.proto

package api_def

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Backup_AllKVsBackup_FullMethodName    = "/api_def.Backup/AllKVsBackup"
	Backup_AllKVsRestore_FullMethodName   = "/api_def.Backup/AllKVsRestore"
	Backup_Snapshot_FullMethodName        = "/api_def.Backup/Snapshot"
	Backup_SnapshotInfo_FullMethodName    = "/api_def.Backup/SnapshotInfo"
	Backup_SnapshotRestore_FullMethodName = "/api_def.Backup/SnapshotRestore"
)

// BackupClient is the client API for Backup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackupClient interface {
	AllKVsBackup(ctx context.Context, in *AllKVsBackup_Input, opts ...grpc.CallOption) (*AllKVsBackup_Output, error)
	AllKVsRestore(ctx context.Context, in *AllKVsRestore_Input, opts ...grpc.CallOption) (*AllKVsRestore_Output, error)
	Snapshot(ctx context.Context, in *Snapshot_Input, opts ...grpc.CallOption) (*Snapshot_Output, error)
	SnapshotInfo(ctx context.Context, in *SnapshotInfo_Input, opts ...grpc.CallOption) (*SnapshotInfo_Output, error)
	SnapshotRestore(ctx context.Context, in *SnapshotRestore_Input, opts ...grpc.CallOption) (*SnapshotRestore_Output, error)
}

type backupClient struct {
	cc grpc.ClientConnInterface
}

func NewBackupClient(cc grpc.ClientConnInterface) BackupClient {
	return &backupClient{cc}
}

func (c *backupClient) AllKVsBackup(ctx context.Context, in *AllKVsBackup_Input, opts ...grpc.CallOption) (*AllKVsBackup_Output, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllKVsBackup_Output)
	err := c.cc.Invoke(ctx, Backup_AllKVsBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupClient) AllKVsRestore(ctx context.Context, in *AllKVsRestore_Input, opts ...grpc.CallOption) (*AllKVsRestore_Output, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllKVsRestore_Output)
	err := c.cc.Invoke(ctx, Backup_AllKVsRestore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupClient) Snapshot(ctx context.Context, in *Snapshot_Input, opts ...grpc.CallOption) (*Snapshot_Output, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot_Output)
	err := c.cc.Invoke(ctx, Backup_Snapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupClient) SnapshotInfo(ctx context.Context, in *SnapshotInfo_Input, opts ...grpc.CallOption) (*SnapshotInfo_Output, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotInfo_Output)
	err := c.cc.Invoke(ctx, Backup_SnapshotInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupClient) SnapshotRestore(ctx context.Context, in *SnapshotRestore_Input, opts ...grpc.CallOption) (*SnapshotRestore_Output, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotRestore_Output)
	err := c.cc.Invoke(ctx, Backup_SnapshotRestore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackupServer is the server API for Backup service.
// All implementations must embed UnimplementedBackupServer
// for forward compatibility.
type BackupServer interface {
	AllKVsBackup(context.Context, *AllKVsBackup_Input) (*AllKVsBackup_Output, error)
	AllKVsRestore(context.Context, *AllKVsRestore_Input) (*AllKVsRestore_Output, error)
	Snapshot(context.Context, *Snapshot_Input) (*Snapshot_Output, error)
	SnapshotInfo(context.Context, *SnapshotInfo_Input) (*SnapshotInfo_Output, error)
	SnapshotRestore(context.Context, *SnapshotRestore_Input) (*SnapshotRestore_Output, error)
	mustEmbedUnimplementedBackupServer()
}

// UnimplementedBackupServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackupServer struct{}

func (UnimplementedBackupServer) AllKVsBackup(context.Context, *AllKVsBackup_Input) (*AllKVsBackup_Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllKVsBackup not implemented")
}
func (UnimplementedBackupServer) AllKVsRestore(context.Context, *AllKVsRestore_Input) (*AllKVsRestore_Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllKVsRestore not implemented")
}
func (UnimplementedBackupServer) Snapshot(context.Context, *Snapshot_Input) (*Snapshot_Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedBackupServer) SnapshotInfo(context.Context, *SnapshotInfo_Input) (*SnapshotInfo_Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SnapshotInfo not implemented")
}
func (UnimplementedBackupServer) SnapshotRestore(context.Context, *SnapshotRestore_Input) (*SnapshotRestore_Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SnapshotRestore not implemented")
}
func (UnimplementedBackupServer) mustEmbedUnimplementedBackupServer() {}
func (UnimplementedBackupServer) testEmbeddedByValue()                {}

// UnsafeBackupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackupServer will
// result in compilation errors.
type UnsafeBackupServer interface {
	mustEmbedUnimplementedBackupServer()
}

func RegisterBackupServer(s grpc.ServiceRegistrar, srv BackupServer) {
	// If the following call pancis, it indicates UnimplementedBackupServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Backup_ServiceDesc, srv)
}

func _Backup_AllKVsBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllKVsBackup_Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServer).AllKVsBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backup_AllKVsBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServer).AllKVsBackup(ctx, req.(*AllKVsBackup_Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backup_AllKVsRestore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllKVsRestore_Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServer).AllKVsRestore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backup_AllKVsRestore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServer).AllKVsRestore(ctx, req.(*AllKVsRestore_Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backup_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Snapshot_Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backup_Snapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServer).Snapshot(ctx, req.(*Snapshot_Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backup_SnapshotInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotInfo_Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServer).SnapshotInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backup_SnapshotInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServer).SnapshotInfo(ctx, req.(*SnapshotInfo_Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backup_SnapshotRestore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRestore_Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServer).SnapshotRestore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backup_SnapshotRestore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServer).SnapshotRestore(ctx, req.(*SnapshotRestore_Input))
	}
	return interceptor(ctx, in, info, handler)
}

// Backup_ServiceDesc is the grpc.ServiceDesc for Backup service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Backup_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api_def.Backup",
	HandlerType: (*BackupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllKVsBackup",
			Handler:    _Backup_AllKVsBackup_Handler,
		},
		{
			MethodName: "AllKVsRestore",
			Handler:    _Backup_AllKVsRestore_Handler,
		},
		{
			MethodName: "Snapshot",
			Handler:    _Backup_Snapshot_Handler,
		},
		{
			MethodName: "SnapshotInfo",
			Handler:    _Backup_SnapshotInfo_Handler,
		},
		{
			MethodName: "SnapshotRestore",
			Handler:    _Backup_SnapshotRestore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/service_hub/backup/api_def/service.proto",
}
