// Code generated by kk_api_gen. DO NOT EDIT.

package allKVsRestore

import (
	"gitee.com/cruvie/kk_go_kit/kk_http"
	"gitee.com/cruvie/kk_go_kit/kk_http/kk_global_stage"
	"gitee.com/cruvie/kk_go_kit/kk_stage"
	"github.com/gin-gonic/gin"
)

type api struct {
	stage *kk_stage.Stage
	In    *AllKVsRestore_Input
}

func NewApi(stage *kk_stage.Stage) *api {
	return &api{
		stage: stage,
		In:    new(AllKVsRestore_Input),
	}
}

//	 Handler
//		@Tags			backup
//		@ID				AllKVsRestore
//		@Description	all kvs restore
//		@Accept			json,application/x-protobuf
//		@Produce		json,application/x-protobuf
//		@Param			AllKVsRestore_Input	body		AllKVsRestore_Input	true	"AllKVsRestore_Input"
//		@Success		200					{object}	AllKVsRestore_Output
//		@Router			/backup/allKVsRestore [post]
func Handler(c *gin.Context) {
	x := NewApi(kk_global_stage.GetRequestStage(c))
	span := x.stage.StartTrace("allKVsRestore")
	defer span.End()

	if err := x.bindCheck(); err != nil {
		kk_http.WriteResponse(x.stage, err, nil)
		return
	}
	resp, err := x.Handler()
	kk_http.WriteResponse(x.stage, err, resp)
}
