// Code generated by kk_api_gen. DO NOT EDIT.

package userList

import (
	"gitee.com/cruvie/kk_go_kit/kk_http"
	"gitee.com/cruvie/kk_go_kit/kk_http/kk_global_stage"
	"gitee.com/cruvie/kk_go_kit/kk_stage"
	"github.com/gin-gonic/gin"
)

type api struct {
	stage *kk_stage.Stage
	in    *UserList_Input
}

func newApi(c *gin.Context) *api {
	return &api{
		stage: kk_global_stage.GetRequestStage(c),
		in:    new(UserList_Input),
	}
}

//  Handler
//	@Tags			user
//	@ID				UserList
//	@Description	list user
//	@Accept			json,application/x-protobuf
//	@Produce		json,application/x-protobuf
//	@Param			UserList_Input	body		UserList_Input	true	"UserList_Input"
//	@Success		200				{object}	UserList_Output
//	@Router			/user/userList [post]
func Handler(c *gin.Context) {
		x := newApi(c)
		span := x.stage.StartTrace("userList")
		defer span.End()
	
		if err := x.bindCheck(x.stage); err != nil {
			kk_http.WriteResponse(x.stage, err, nil)
			return
		}
		err, resp := x.handler()
		kk_http.WriteResponse(x.stage, err, resp)
}