// Code generated by kk_api_gen. DO NOT EDIT.

package userDelete

import (
	"gitee.com/cruvie/kk_go_kit/kk_http"
	"gitee.com/cruvie/kk_go_kit/kk_http/kk_global_stage"
	"gitee.com/cruvie/kk_go_kit/kk_stage"
	"github.com/gin-gonic/gin"
)

type api struct {
	stage *kk_stage.Stage
	In    *UserDelete_Input
}

func NewApi(stage *kk_stage.Stage) *api {
	return &api{
		stage: stage,
		In:    new(UserDelete_Input),
	}
}

//  Handler
//	@Tags			user
//	@ID				UserDelete
//	@Description	delete user
//	@Accept			json,application/x-protobuf
//	@Produce		json,application/x-protobuf
//	@Param			UserDelete_Input	body		UserDelete_Input	true	"UserDelete_Input"
//	@Success		200					{object}	UserDelete_Output
//	@Router			/user/userDelete [post]
func Handler(c *gin.Context) {
		x := NewApi(kk_global_stage.GetRequestStage(c))
		span := x.stage.StartTrace("userDelete")
		defer span.End()
	
		if err := x.bindCheck(); err != nil {
			kk_http.WriteResponse(x.stage, err, nil)
			return
		}
		err, resp := x.Handler()
		kk_http.WriteResponse(x.stage, err, resp)
}