// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: internal/service_hub/service/api_def/service.proto

package api_def

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_internal_service_hub_service_api_def_service_proto protoreflect.FileDescriptor

const file_internal_service_hub_service_api_def_service_proto_rawDesc = "" +
	"\n" +
	"2internal/service_hub/service/api_def/service.proto\x12\aapi_def\x1a<internal/service_hub/service/api_def/DeregisterService.proto\x1a6internal/service_hub/service/api_def/ServiceList.proto2\xab\x01\n" +
	"\aService\x12X\n" +
	"\x11DeregisterService\x12 .api_def.DeregisterService.Input\x1a!.api_def.DeregisterService.Output\x12F\n" +
	"\vServiceList\x12\x1a.api_def.ServiceList.Input\x1a\x1b.api_def.ServiceList.OutputB\n" +
	"Z\b/api_defb\x06proto3"

var file_internal_service_hub_service_api_def_service_proto_goTypes = []any{
	(*DeregisterService_Input)(nil),  // 0: api_def.DeregisterService.Input
	(*ServiceList_Input)(nil),        // 1: api_def.ServiceList.Input
	(*DeregisterService_Output)(nil), // 2: api_def.DeregisterService.Output
	(*ServiceList_Output)(nil),       // 3: api_def.ServiceList.Output
}
var file_internal_service_hub_service_api_def_service_proto_depIdxs = []int32{
	0, // 0: api_def.Service.DeregisterService:input_type -> api_def.DeregisterService.Input
	1, // 1: api_def.Service.ServiceList:input_type -> api_def.ServiceList.Input
	2, // 2: api_def.Service.DeregisterService:output_type -> api_def.DeregisterService.Output
	3, // 3: api_def.Service.ServiceList:output_type -> api_def.ServiceList.Output
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_service_hub_service_api_def_service_proto_init() }
func file_internal_service_hub_service_api_def_service_proto_init() {
	if File_internal_service_hub_service_api_def_service_proto != nil {
		return
	}
	file_internal_service_hub_service_api_def_DeregisterService_proto_init()
	file_internal_service_hub_service_api_def_ServiceList_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_service_hub_service_api_def_service_proto_rawDesc), len(file_internal_service_hub_service_api_def_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_service_hub_service_api_def_service_proto_goTypes,
		DependencyIndexes: file_internal_service_hub_service_api_def_service_proto_depIdxs,
	}.Build()
	File_internal_service_hub_service_api_def_service_proto = out.File
	file_internal_service_hub_service_api_def_service_proto_goTypes = nil
	file_internal_service_hub_service_api_def_service_proto_depIdxs = nil
}
