// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: internal/service_hub/service/api_def/ServiceList.proto

package api_def

import (
	kk_etcd_models "github.com/cruvie/kk_etcd_go/kk_etcd_models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// list server
type ServiceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceList) Reset() {
	*x = ServiceList{}
	mi := &file_internal_service_hub_service_api_def_ServiceList_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceList) ProtoMessage() {}

func (x *ServiceList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_hub_service_api_def_ServiceList_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceList.ProtoReflect.Descriptor instead.
func (*ServiceList) Descriptor() ([]byte, []int) {
	return file_internal_service_hub_service_api_def_ServiceList_proto_rawDescGZIP(), []int{0}
}

type ServiceList_Input struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	ServiceType   kk_etcd_models.PBServiceType `protobuf:"varint,1,opt,name=ServiceType,proto3,enum=kk_etcd_models.PBServiceType" json:"ServiceType,omitempty"`
	ServiceName   string                       `protobuf:"bytes,2,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceList_Input) Reset() {
	*x = ServiceList_Input{}
	mi := &file_internal_service_hub_service_api_def_ServiceList_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceList_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceList_Input) ProtoMessage() {}

func (x *ServiceList_Input) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_hub_service_api_def_ServiceList_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceList_Input.ProtoReflect.Descriptor instead.
func (*ServiceList_Input) Descriptor() ([]byte, []int) {
	return file_internal_service_hub_service_api_def_ServiceList_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ServiceList_Input) GetServiceType() kk_etcd_models.PBServiceType {
	if x != nil {
		return x.ServiceType
	}
	return kk_etcd_models.PBServiceType(0)
}

func (x *ServiceList_Input) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type ServiceList_Output struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	ServiceList   *kk_etcd_models.PBListService `protobuf:"bytes,1,opt,name=ServiceList,proto3" json:"ServiceList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceList_Output) Reset() {
	*x = ServiceList_Output{}
	mi := &file_internal_service_hub_service_api_def_ServiceList_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceList_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceList_Output) ProtoMessage() {}

func (x *ServiceList_Output) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_hub_service_api_def_ServiceList_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceList_Output.ProtoReflect.Descriptor instead.
func (*ServiceList_Output) Descriptor() ([]byte, []int) {
	return file_internal_service_hub_service_api_def_ServiceList_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ServiceList_Output) GetServiceList() *kk_etcd_models.PBListService {
	if x != nil {
		return x.ServiceList
	}
	return nil
}

var File_internal_service_hub_service_api_def_ServiceList_proto protoreflect.FileDescriptor

const file_internal_service_hub_service_api_def_ServiceList_proto_rawDesc = "" +
	"\n" +
	"6internal/service_hub/service/api_def/ServiceList.proto\x12\aapi_def\x1a'kk_etcd_models/pb_service_kk_etcd.proto\x1a,kk_etcd_models/pb_service_registration.proto\"\xc4\x01\n" +
	"\vServiceList\x1aj\n" +
	"\x05Input\x12?\n" +
	"\vServiceType\x18\x01 \x01(\x0e2\x1d.kk_etcd_models.PBServiceTypeR\vServiceType\x12 \n" +
	"\vServiceName\x18\x02 \x01(\tR\vServiceName\x1aI\n" +
	"\x06Output\x12?\n" +
	"\vServiceList\x18\x01 \x01(\v2\x1d.kk_etcd_models.PBListServiceR\vServiceListB\n" +
	"Z\b/api_defb\x06proto3"

var (
	file_internal_service_hub_service_api_def_ServiceList_proto_rawDescOnce sync.Once
	file_internal_service_hub_service_api_def_ServiceList_proto_rawDescData []byte
)

func file_internal_service_hub_service_api_def_ServiceList_proto_rawDescGZIP() []byte {
	file_internal_service_hub_service_api_def_ServiceList_proto_rawDescOnce.Do(func() {
		file_internal_service_hub_service_api_def_ServiceList_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_service_hub_service_api_def_ServiceList_proto_rawDesc), len(file_internal_service_hub_service_api_def_ServiceList_proto_rawDesc)))
	})
	return file_internal_service_hub_service_api_def_ServiceList_proto_rawDescData
}

var file_internal_service_hub_service_api_def_ServiceList_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_service_hub_service_api_def_ServiceList_proto_goTypes = []any{
	(*ServiceList)(nil),                  // 0: api_def.ServiceList
	(*ServiceList_Input)(nil),            // 1: api_def.ServiceList.Input
	(*ServiceList_Output)(nil),           // 2: api_def.ServiceList.Output
	(kk_etcd_models.PBServiceType)(0),    // 3: kk_etcd_models.PBServiceType
	(*kk_etcd_models.PBListService)(nil), // 4: kk_etcd_models.PBListService
}
var file_internal_service_hub_service_api_def_ServiceList_proto_depIdxs = []int32{
	3, // 0: api_def.ServiceList.Input.ServiceType:type_name -> kk_etcd_models.PBServiceType
	4, // 1: api_def.ServiceList.Output.ServiceList:type_name -> kk_etcd_models.PBListService
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_service_hub_service_api_def_ServiceList_proto_init() }
func file_internal_service_hub_service_api_def_ServiceList_proto_init() {
	if File_internal_service_hub_service_api_def_ServiceList_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_service_hub_service_api_def_ServiceList_proto_rawDesc), len(file_internal_service_hub_service_api_def_ServiceList_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_service_hub_service_api_def_ServiceList_proto_goTypes,
		DependencyIndexes: file_internal_service_hub_service_api_def_ServiceList_proto_depIdxs,
		MessageInfos:      file_internal_service_hub_service_api_def_ServiceList_proto_msgTypes,
	}.Build()
	File_internal_service_hub_service_api_def_ServiceList_proto = out.File
	file_internal_service_hub_service_api_def_ServiceList_proto_goTypes = nil
	file_internal_service_hub_service_api_def_ServiceList_proto_depIdxs = nil
}
