// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: kk_etcd_api_hub/kv/api_def/KVDel.proto

package api_def

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// del kv
type KVDel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVDel) Reset() {
	*x = KVDel{}
	mi := &file_kk_etcd_api_hub_kv_api_def_KVDel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVDel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVDel) ProtoMessage() {}

func (x *KVDel) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_kv_api_def_KVDel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVDel.ProtoReflect.Descriptor instead.
func (*KVDel) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_kv_api_def_KVDel_proto_rawDescGZIP(), []int{0}
}

type KVDel_Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVDel_Input) Reset() {
	*x = KVDel_Input{}
	mi := &file_kk_etcd_api_hub_kv_api_def_KVDel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVDel_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVDel_Input) ProtoMessage() {}

func (x *KVDel_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_kv_api_def_KVDel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVDel_Input.ProtoReflect.Descriptor instead.
func (*KVDel_Input) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_kv_api_def_KVDel_proto_rawDescGZIP(), []int{0, 0}
}

func (x *KVDel_Input) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KVDel_Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVDel_Output) Reset() {
	*x = KVDel_Output{}
	mi := &file_kk_etcd_api_hub_kv_api_def_KVDel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVDel_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVDel_Output) ProtoMessage() {}

func (x *KVDel_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_kv_api_def_KVDel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVDel_Output.ProtoReflect.Descriptor instead.
func (*KVDel_Output) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_kv_api_def_KVDel_proto_rawDescGZIP(), []int{0, 1}
}

var File_kk_etcd_api_hub_kv_api_def_KVDel_proto protoreflect.FileDescriptor

const file_kk_etcd_api_hub_kv_api_def_KVDel_proto_rawDesc = "" +
	"\n" +
	"&kk_etcd_api_hub/kv/api_def/KVDel.proto\x12\aapi_def\",\n" +
	"\x05KVDel\x1a\x19\n" +
	"\x05Input\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x1a\b\n" +
	"\x06OutputB\n" +
	"Z\b/api_defb\x06proto3"

var (
	file_kk_etcd_api_hub_kv_api_def_KVDel_proto_rawDescOnce sync.Once
	file_kk_etcd_api_hub_kv_api_def_KVDel_proto_rawDescData []byte
)

func file_kk_etcd_api_hub_kv_api_def_KVDel_proto_rawDescGZIP() []byte {
	file_kk_etcd_api_hub_kv_api_def_KVDel_proto_rawDescOnce.Do(func() {
		file_kk_etcd_api_hub_kv_api_def_KVDel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kk_etcd_api_hub_kv_api_def_KVDel_proto_rawDesc), len(file_kk_etcd_api_hub_kv_api_def_KVDel_proto_rawDesc)))
	})
	return file_kk_etcd_api_hub_kv_api_def_KVDel_proto_rawDescData
}

var file_kk_etcd_api_hub_kv_api_def_KVDel_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kk_etcd_api_hub_kv_api_def_KVDel_proto_goTypes = []any{
	(*KVDel)(nil),        // 0: api_def.KVDel
	(*KVDel_Input)(nil),  // 1: api_def.KVDel.Input
	(*KVDel_Output)(nil), // 2: api_def.KVDel.Output
}
var file_kk_etcd_api_hub_kv_api_def_KVDel_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kk_etcd_api_hub_kv_api_def_KVDel_proto_init() }
func file_kk_etcd_api_hub_kv_api_def_KVDel_proto_init() {
	if File_kk_etcd_api_hub_kv_api_def_KVDel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_etcd_api_hub_kv_api_def_KVDel_proto_rawDesc), len(file_kk_etcd_api_hub_kv_api_def_KVDel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_etcd_api_hub_kv_api_def_KVDel_proto_goTypes,
		DependencyIndexes: file_kk_etcd_api_hub_kv_api_def_KVDel_proto_depIdxs,
		MessageInfos:      file_kk_etcd_api_hub_kv_api_def_KVDel_proto_msgTypes,
	}.Build()
	File_kk_etcd_api_hub_kv_api_def_KVDel_proto = out.File
	file_kk_etcd_api_hub_kv_api_def_KVDel_proto_goTypes = nil
	file_kk_etcd_api_hub_kv_api_def_KVDel_proto_depIdxs = nil
}
