ServerAddr: :2333
DebugMode: true
# RootPassword is the password of root user in etcd
#  if you didn't set the password of root user in etcd, leave it blank
RootPassword:
Admin:
  UserName: kk_etcd # username cannot be root
  Password: kk_etcd
Etcd:
  Endpoint: http://127.0.0.1:2379
JWT:
  Key: You are re on your way to prison
  ExpireTime: 24