// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: kk_etcd_api_hub/server/api_def/DeregisterServer.proto

package api_def

import (
	kk_etcd_models "github.com/cruvie/kk_etcd_go/kk_etcd_models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// deregister server
type DeregisterServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterServer) Reset() {
	*x = DeregisterServer{}
	mi := &file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterServer) ProtoMessage() {}

func (x *DeregisterServer) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterServer.ProtoReflect.Descriptor instead.
func (*DeregisterServer) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_rawDescGZIP(), []int{0}
}

type DeregisterServer_Input struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Server        *kk_etcd_models.PBServer `protobuf:"bytes,1,opt,name=Server,proto3" json:"Server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterServer_Input) Reset() {
	*x = DeregisterServer_Input{}
	mi := &file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterServer_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterServer_Input) ProtoMessage() {}

func (x *DeregisterServer_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterServer_Input.ProtoReflect.Descriptor instead.
func (*DeregisterServer_Input) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DeregisterServer_Input) GetServer() *kk_etcd_models.PBServer {
	if x != nil {
		return x.Server
	}
	return nil
}

type DeregisterServer_Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterServer_Output) Reset() {
	*x = DeregisterServer_Output{}
	mi := &file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterServer_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterServer_Output) ProtoMessage() {}

func (x *DeregisterServer_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterServer_Output.ProtoReflect.Descriptor instead.
func (*DeregisterServer_Output) Descriptor() ([]byte, []int) {
	return file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_rawDescGZIP(), []int{0, 1}
}

var File_kk_etcd_api_hub_server_api_def_DeregisterServer_proto protoreflect.FileDescriptor

const file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_rawDesc = "" +
	"\n" +
	"5kk_etcd_api_hub/server/api_def/DeregisterServer.proto\x12\aapi_def\x1a&kk_etcd_models/pb_server_kk_etcd.proto\"W\n" +
	"\x10DeregisterServer\x1a9\n" +
	"\x05Input\x120\n" +
	"\x06Server\x18\x01 \x01(\v2\x18.kk_etcd_models.PBServerR\x06Server\x1a\b\n" +
	"\x06OutputB\n" +
	"Z\b/api_defb\x06proto3"

var (
	file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_rawDescOnce sync.Once
	file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_rawDescData []byte
)

func file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_rawDescGZIP() []byte {
	file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_rawDescOnce.Do(func() {
		file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_rawDesc), len(file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_rawDesc)))
	})
	return file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_rawDescData
}

var file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_goTypes = []any{
	(*DeregisterServer)(nil),        // 0: api_def.DeregisterServer
	(*DeregisterServer_Input)(nil),  // 1: api_def.DeregisterServer.Input
	(*DeregisterServer_Output)(nil), // 2: api_def.DeregisterServer.Output
	(*kk_etcd_models.PBServer)(nil), // 3: kk_etcd_models.PBServer
}
var file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_depIdxs = []int32{
	3, // 0: api_def.DeregisterServer.Input.Server:type_name -> kk_etcd_models.PBServer
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_init() }
func file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_init() {
	if File_kk_etcd_api_hub_server_api_def_DeregisterServer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_rawDesc), len(file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_goTypes,
		DependencyIndexes: file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_depIdxs,
		MessageInfos:      file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_msgTypes,
	}.Build()
	File_kk_etcd_api_hub_server_api_def_DeregisterServer_proto = out.File
	file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_goTypes = nil
	file_kk_etcd_api_hub_server_api_def_DeregisterServer_proto_depIdxs = nil
}
