// Code generated by kk_api_gen. DO NOT EDIT.

package kVDel

import (
	"gitee.com/cruvie/kk_go_kit/kk_http"
	"gitee.com/cruvie/kk_go_kit/kk_http/kk_global_stage"
	"gitee.com/cruvie/kk_go_kit/kk_stage"
	"github.com/gin-gonic/gin"
)

type api struct {
	stage *kk_stage.Stage
	in    *KVDel_Input
}

func newApi(c *gin.Context) *api {
	return &api{
		stage: kk_global_stage.GetRequestStage(c),
		in:    new(KVDel_Input),
	}
}

//  Handler
//	@Tags			kv
//	@ID				KVDel
//	@Description	del kv
//	@Accept			json,application/x-protobuf
//	@Produce		json,application/x-protobuf
//	@Param			KVDel_Input	body		KVDel_Input	true	"KVDel_Input"
//	@Success		200			{object}	KVDel_Output
//	@Router			/kv/kVDel [post]
func Handler(c *gin.Context) {
		x := newApi(c)
		span := x.stage.StartTrace("kVDel")
		defer span.End()
	
		if err := x.bindCheck(x.stage); err != nil {
			kk_http.WriteResponse(x.stage, err, nil)
			return
		}
		err, resp := x.handler()
		kk_http.WriteResponse(x.stage, err, resp)
}