// Code generated by kk_etcd_go. DO NOT EDIT.

package api_impl

import (
	"context"

	"gitee.com/cruvie/kk_go_kit/kk_grpc"
	"github.com/cruvie/kk_etcd_go/internal/service_hub/user/api_def"
	"github.com/cruvie/kk_etcd_go/internal/utils/internal_client"
)

type CServer struct {
	api_def.UnimplementedUserServer
	ins server
}

func (x *CServer) GetUser(ctx context.Context, input *api_def.GetUser_Input) (*api_def.GetUser_Output, error) {
	ctx = kk_grpc.SetGrpcStage(ctx, internal_client.GlobalStage)
	return x.ins.GetUser(ctx, input)
}

func (x *CServer) Login(ctx context.Context, input *api_def.Login_Input) (*api_def.Login_Output, error) {
	ctx = kk_grpc.SetGrpcStage(ctx, internal_client.GlobalStage)
	return x.ins.Login(ctx, input)
}

func (x *CServer) Logout(ctx context.Context, input *api_def.Logout_Input) (*api_def.Logout_Output, error) {
	ctx = kk_grpc.SetGrpcStage(ctx, internal_client.GlobalStage)
	return x.ins.Logout(ctx, input)
}

func (x *CServer) MyInfo(ctx context.Context, input *api_def.MyInfo_Input) (*api_def.MyInfo_Output, error) {
	ctx = kk_grpc.SetGrpcStage(ctx, internal_client.GlobalStage)
	return x.ins.MyInfo(ctx, input)
}

func (x *CServer) UserAdd(ctx context.Context, input *api_def.UserAdd_Input) (*api_def.UserAdd_Output, error) {
	ctx = kk_grpc.SetGrpcStage(ctx, internal_client.GlobalStage)
	return x.ins.UserAdd(ctx, input)
}

func (x *CServer) UserDelete(ctx context.Context, input *api_def.UserDelete_Input) (*api_def.UserDelete_Output, error) {
	ctx = kk_grpc.SetGrpcStage(ctx, internal_client.GlobalStage)
	return x.ins.UserDelete(ctx, input)
}

func (x *CServer) UserGrantRole(ctx context.Context, input *api_def.UserGrantRole_Input) (*api_def.UserGrantRole_Output, error) {
	ctx = kk_grpc.SetGrpcStage(ctx, internal_client.GlobalStage)
	return x.ins.UserGrantRole(ctx, input)
}

func (x *CServer) UserList(ctx context.Context, input *api_def.UserList_Input) (*api_def.UserList_Output, error) {
	ctx = kk_grpc.SetGrpcStage(ctx, internal_client.GlobalStage)
	return x.ins.UserList(ctx, input)
}
