// Code generated by kk_etcd_go. DO NOT EDIT.

package api_impl

import (
	"context"

	"gitee.com/cruvie/kk_go_kit/kk_grpc"
	"github.com/cruvie/kk_etcd_go/internal/service_hub/service/api_def"
	"github.com/cruvie/kk_etcd_go/internal/utils/internal_client"
)

type CServer struct {
	api_def.UnimplementedServiceServer
	ins server
}

func (x *CServer) DeregisterService(ctx context.Context, input *api_def.DeregisterService_Input) (*api_def.DeregisterService_Output, error) {
	ctx = kk_grpc.SetGrpcStage(ctx, internal_client.GlobalStage)
	return x.ins.DeregisterService(ctx, input)
}

func (x *CServer) ServiceList(ctx context.Context, input *api_def.ServiceList_Input) (*api_def.ServiceList_Output, error) {
	ctx = kk_grpc.SetGrpcStage(ctx, internal_client.GlobalStage)
	return x.ins.ServiceList(ctx, input)
}
